import type { Prisma, PrismaClient } from '../../src/generated/client'

type Tx = Parameters<Parameters<PrismaClient['$transaction']>[0]>[0]

interface SeedEntry {
  key: string
  name: string
  description: string
  family: string | null
  tier: number
  hidden: boolean
  sortOrder: number
  criterion: Prisma.InputJsonValue
  reward: { tokens: number; dust: number; xp: number; cardRarity?: string }
}

const ENTRIES: SeedEntry[] = [
  // pulls
  {
    key: 'pulls_10',
    name: 'Mise en jambes',
    description: 'Réaliser 10 tirages.',
    family: 'pulls',
    tier: 0,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'PULL_COUNT', threshold: 10 },
    reward: { tokens: 2, dust: 0, xp: 0 },
  },
  {
    key: 'pulls_100',
    name: 'Habitué·e',
    description: 'Réaliser 100 tirages.',
    family: 'pulls',
    tier: 1,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'PULL_COUNT', threshold: 100 },
    reward: { tokens: 4, dust: 30, xp: 0 },
  },
  {
    key: 'pulls_500',
    name: 'Accro aux tirages',
    description: 'Réaliser 500 tirages.',
    family: 'pulls',
    tier: 2,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'PULL_COUNT', threshold: 500 },
    reward: { tokens: 10, dust: 100, xp: 50 },
  },
  {
    key: 'pulls_1000',
    name: 'Légende du gachapon',
    description: 'Réaliser 1 000 tirages.',
    family: 'pulls',
    tier: 3,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'PULL_COUNT', threshold: 1000 },
    reward: { tokens: 50, dust: 250, xp: 0, cardRarity: 'RARE' },
  },

  // dust
  {
    key: 'dust_spent_500',
    name: 'Premier investissement',
    description: 'Dépenser 500 de poussière.',
    family: 'dust',
    tier: 0,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'DUST_SPENT', threshold: 500 },
    reward: { tokens: 2, dust: 0, xp: 0 },
  },
  {
    key: 'dust_spent_5000',
    name: 'Grand dépensier',
    description: 'Dépenser 5 000 de poussière.',
    family: 'dust',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'DUST_SPENT', threshold: 5000 },
    reward: { tokens: 10, dust: 100, xp: 50 },
  },
  {
    key: 'cards_recycled_50',
    name: 'Recycleur',
    description: 'Recycler 50 cartes.',
    family: 'dust',
    tier: 1,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'CARDS_RECYCLED', threshold: 50 },
    reward: { tokens: 4, dust: 30, xp: 0 },
  },

  // collection_rarity
  {
    key: 'own_rare_10',
    name: 'Chasseur de raretés',
    description: 'Posséder 10 cartes rares.',
    family: 'collection_rarity',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'RARE', threshold: 10 },
    reward: { tokens: 4, dust: 30, xp: 0 },
  },
  {
    key: 'own_epic_5',
    name: "Amateur d'épiques",
    description: 'Posséder 5 cartes épiques.',
    family: 'collection_rarity',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'EPIC', threshold: 5 },
    reward: { tokens: 10, dust: 100, xp: 50 },
  },
  {
    key: 'own_legendary_1',
    name: 'Première légende',
    description: 'Posséder 1 carte légendaire.',
    family: 'collection_rarity',
    tier: 2,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'LEGENDARY', threshold: 1 },
    reward: { tokens: 10, dust: 100, xp: 50 },
  },
  {
    key: 'own_legendary_5',
    name: 'Légende confirmée',
    description: 'Posséder 5 cartes légendaires.',
    family: 'collection_rarity',
    tier: 3,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'LEGENDARY', threshold: 5 },
    reward: { tokens: 50, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_holographic_1',
    name: 'Holographie',
    description: 'Posséder 1 carte holographique.',
    family: 'collection_rarity',
    tier: 2,
    hidden: false,
    sortOrder: 5,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'HOLOGRAPHIC',
      threshold: 1,
    },
    reward: { tokens: 20, dust: 100, xp: 50 },
  },

  // collection_variants
  {
    key: 'own_brilliant_1',
    name: 'Premier éclat',
    description: 'Posséder 1 carte brillante.',
    family: 'collection_variants',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'OWN_RARITY_COUNT', variant: 'BRILLIANT', threshold: 1 },
    reward: { tokens: 8, dust: 30, xp: 0 },
  },
  {
    key: 'own_brilliant_5',
    name: 'Éclat persistant',
    description: 'Posséder 5 cartes brillantes.',
    family: 'collection_variants',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'OWN_RARITY_COUNT', variant: 'BRILLIANT', threshold: 5 },
    reward: { tokens: 20, dust: 100, xp: 50 },
  },
  {
    key: 'same_card_two_variants',
    name: 'Double face',
    description: "Posséder 2 variantes d'une même carte.",
    family: 'collection_variants',
    tier: 2,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'CUSTOM_EVENT', handlerKey: 'same_card_two_variants' },
    reward: { tokens: 20, dust: 100, xp: 50 },
  },

  // collection_complete
  {
    key: 'complete_common',
    name: 'Collection commune',
    description: 'Posséder toutes les cartes communes.',
    family: 'collection_complete',
    tier: 3,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'COLLECTION_COMPLETE', scope: { rarity: 'COMMON' } },
    reward: { tokens: 50, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'complete_1_set',
    name: 'Set complet',
    description: 'Compléter entièrement un set de cartes.',
    family: 'collection_sets',
    tier: 3,
    hidden: false,
    sortOrder: 0,
    criterion: { type: 'SETS_COMPLETED', threshold: 1 },
    reward: { tokens: 25, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'complete_3_sets',
    name: 'Collectionneur chevronné',
    description: 'Compléter entièrement 3 sets de cartes.',
    family: 'collection_sets',
    tier: 4,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'SETS_COMPLETED', threshold: 3 },
    reward: { tokens: 100, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'complete_5_sets',
    name: 'Maître collectionneur',
    description: 'Compléter entièrement 5 sets de cartes.',
    family: 'collection_sets',
    tier: 5,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'SETS_COMPLETED', threshold: 5 },
    reward: { tokens: 200, dust: 1000, xp: 0, cardRarity: 'LEGENDARY' },
  },

  // streak
  {
    key: 'streak_30',
    name: 'Mois complet',
    description: 'Atteindre 30 jours de série.',
    family: 'streak',
    tier: 4,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'STREAK_REACHED', threshold: 30 },
    reward: { tokens: 100, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },

  // pulls (suite)
  {
    key: 'pulls_2500',
    name: "Tireur d'élite",
    description: 'Réaliser 2 500 tirages.',
    family: 'pulls',
    tier: 4,
    hidden: false,
    sortOrder: 5,
    criterion: { type: 'PULL_COUNT', threshold: 2500 },
    reward: { tokens: 100, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'pulls_5000',
    name: 'Divinité du gachapon',
    description: 'Réaliser 5 000 tirages.',
    family: 'pulls',
    tier: 5,
    hidden: false,
    sortOrder: 6,
    criterion: { type: 'PULL_COUNT', threshold: 5000 },
    reward: { tokens: 200, dust: 1000, xp: 0, cardRarity: 'LEGENDARY' },
  },

  // dust (suite)
  {
    key: 'dust_spent_50000',
    name: 'Magnat de la poussière',
    description: 'Dépenser 50 000 de poussière.',
    family: 'dust',
    tier: 4,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'DUST_SPENT', threshold: 50000 },
    reward: { tokens: 100, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'cards_recycled_250',
    name: 'Grand recycleur',
    description: 'Recycler 250 cartes.',
    family: 'dust',
    tier: 3,
    hidden: false,
    sortOrder: 5,
    criterion: { type: 'CARDS_RECYCLED', threshold: 250 },
    reward: { tokens: 50, dust: 250, xp: 0, cardRarity: 'RARE' },
  },

  // collection_rarity (suite)
  {
    key: 'own_rare_25',
    name: 'Collectionneur de raretés',
    description: 'Posséder 25 cartes rares.',
    family: 'collection_rarity',
    tier: 2,
    hidden: false,
    sortOrder: 6,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'RARE', threshold: 25 },
    reward: { tokens: 20, dust: 100, xp: 50 },
  },
  {
    key: 'own_rare_50',
    name: 'Maître des raretés',
    description: 'Posséder 50 cartes rares.',
    family: 'collection_rarity',
    tier: 3,
    hidden: false,
    sortOrder: 7,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'RARE', threshold: 50 },
    reward: { tokens: 50, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_epic_15',
    name: "Amateur confirmé d'épiques",
    description: 'Posséder 15 cartes épiques.',
    family: 'collection_rarity',
    tier: 3,
    hidden: false,
    sortOrder: 8,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'EPIC', threshold: 15 },
    reward: { tokens: 50, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_epic_30',
    name: 'Maître des épiques',
    description: 'Posséder 30 cartes épiques.',
    family: 'collection_rarity',
    tier: 4,
    hidden: false,
    sortOrder: 9,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'EPIC', threshold: 30 },
    reward: { tokens: 100, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'own_legendary_10',
    name: 'Panthéon',
    description: 'Posséder 10 cartes légendaires.',
    family: 'collection_rarity',
    tier: 4,
    hidden: false,
    sortOrder: 10,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'LEGENDARY', threshold: 10 },
    reward: { tokens: 100, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'own_legendary_20',
    name: 'Olympe',
    description: 'Posséder 20 cartes légendaires.',
    family: 'collection_rarity',
    tier: 5,
    hidden: false,
    sortOrder: 11,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'LEGENDARY', threshold: 20 },
    reward: { tokens: 200, dust: 1000, xp: 0, cardRarity: 'LEGENDARY' },
  },
  {
    key: 'own_holographic_3',
    name: 'Reflets multiples',
    description: 'Posséder 3 cartes holographiques.',
    family: 'collection_rarity',
    tier: 3,
    hidden: false,
    sortOrder: 12,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'HOLOGRAPHIC',
      threshold: 3,
    },
    reward: { tokens: 50, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_holographic_10',
    name: 'Prisme complet',
    description: 'Posséder 10 cartes holographiques.',
    family: 'collection_rarity',
    tier: 4,
    hidden: false,
    sortOrder: 13,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'HOLOGRAPHIC',
      threshold: 10,
    },
    reward: { tokens: 100, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },

  // collection_variants (suite)
  {
    key: 'own_brilliant_15',
    name: 'Éclat rayonnant',
    description: 'Posséder 15 cartes brillantes.',
    family: 'collection_variants',
    tier: 3,
    hidden: false,
    sortOrder: 4,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'BRILLIANT',
      threshold: 15,
    },
    reward: { tokens: 50, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_brilliant_30',
    name: 'Éclat éternel',
    description: 'Posséder 30 cartes brillantes.',
    family: 'collection_variants',
    tier: 4,
    hidden: false,
    sortOrder: 5,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'BRILLIANT',
      threshold: 30,
    },
    reward: { tokens: 100, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },

  // collection_sets (suite)
  {
    key: 'complete_10_sets',
    name: 'Grand maître collectionneur',
    description: 'Compléter entièrement 10 sets de cartes.',
    family: 'collection_sets',
    tier: 5,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'SETS_COMPLETED', threshold: 10 },
    reward: { tokens: 300, dust: 1500, xp: 0, cardRarity: 'LEGENDARY' },
  },

  // streak (suite)
  {
    key: 'streak_60',
    name: "Deux mois d'affilée",
    description: 'Atteindre 60 jours de série.',
    family: 'streak',
    tier: 5,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'STREAK_REACHED', threshold: 60 },
    reward: { tokens: 200, dust: 1000, xp: 0, cardRarity: 'LEGENDARY' },
  },
  {
    key: 'streak_100',
    name: 'Centenaire',
    description: 'Atteindre 100 jours de série.',
    family: 'streak',
    tier: 5,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'STREAK_REACHED', threshold: 100 },
    reward: { tokens: 300, dust: 1500, xp: 0, cardRarity: 'LEGENDARY' },
  },

  // account
  {
    key: 'level_10',
    name: 'Apprenti',
    description: 'Atteindre le niveau 10.',
    family: 'account',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'LEVEL_REACHED', threshold: 10 },
    reward: { tokens: 4, dust: 30, xp: 0 },
  },
  {
    key: 'level_25',
    name: 'Vétéran',
    description: 'Atteindre le niveau 25.',
    family: 'account',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'LEVEL_REACHED', threshold: 25 },
    reward: { tokens: 10, dust: 100, xp: 50 },
  },
  {
    key: 'level_50',
    name: 'Expert',
    description: 'Atteindre le niveau 50.',
    family: 'account',
    tier: 3,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'LEVEL_REACHED', threshold: 50 },
    reward: { tokens: 50, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'level_100',
    name: 'Sommet',
    description: 'Atteindre le niveau 100.',
    family: 'account',
    tier: 4,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'LEVEL_REACHED', threshold: 100 },
    reward: { tokens: 100, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },

  // campaign
  {
    key: 'stages_cleared_25',
    name: 'Éclaireur',
    description: 'Vaincre 25 étages de campagne.',
    family: 'campaign',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'STAGES_CLEARED_COUNT', threshold: 25 },
    reward: { tokens: 8, dust: 30, xp: 0 },
  },
  {
    key: 'stages_cleared_50',
    name: 'Conquérant',
    description: 'Vaincre 50 étages de campagne.',
    family: 'campaign',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'STAGES_CLEARED_COUNT', threshold: 50 },
    reward: { tokens: 20, dust: 100, xp: 50 },
  },
  {
    key: 'stages_cleared_100',
    name: 'Général',
    description: 'Vaincre 100 étages de campagne.',
    family: 'campaign',
    tier: 3,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'STAGES_CLEARED_COUNT', threshold: 100 },
    reward: { tokens: 50, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'boss_defeats_5',
    name: 'Tueur de boss',
    description: 'Vaincre 5 boss.',
    family: 'campaign',
    tier: 1,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'BOSS_DEFEATS_COUNT', threshold: 5 },
    reward: { tokens: 8, dust: 30, xp: 0 },
  },
  {
    key: 'boss_defeats_10',
    name: 'Fléau des boss',
    description: 'Vaincre 10 boss.',
    family: 'campaign',
    tier: 2,
    hidden: false,
    sortOrder: 5,
    criterion: { type: 'BOSS_DEFEATS_COUNT', threshold: 10 },
    reward: { tokens: 20, dust: 100, xp: 50 },
  },
  {
    key: 'boss_defeats_25',
    name: 'Cauchemar des boss',
    description: 'Vaincre 25 boss.',
    family: 'campaign',
    tier: 3,
    hidden: false,
    sortOrder: 6,
    criterion: { type: 'BOSS_DEFEATS_COUNT', threshold: 25 },
    reward: { tokens: 50, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'chapter_reached_2',
    name: 'Nouvel horizon',
    description: 'Atteindre le chapitre 2.',
    family: 'campaign',
    tier: 1,
    hidden: false,
    sortOrder: 7,
    criterion: { type: 'CAMPAIGN_CHAPTER_REACHED', threshold: 2 },
    reward: { tokens: 8, dust: 30, xp: 0 },
  },
  {
    key: 'chapter_reached_3',
    name: 'Terres lointaines',
    description: 'Atteindre le chapitre 3.',
    family: 'campaign',
    tier: 2,
    hidden: false,
    sortOrder: 8,
    criterion: { type: 'CAMPAIGN_CHAPTER_REACHED', threshold: 3 },
    reward: { tokens: 20, dust: 100, xp: 50 },
  },

  // mastery
  {
    key: 'flawless_clears_1',
    name: 'Sans une égratignure',
    description: 'Gagner un combat sans aucune perte.',
    family: 'mastery',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'FLAWLESS_CLEARS_COUNT', threshold: 1 },
    reward: { tokens: 8, dust: 30, xp: 0 },
  },
  {
    key: 'flawless_clears_25',
    name: 'Intouchable',
    description: 'Gagner 25 combats sans aucune perte.',
    family: 'mastery',
    tier: 3,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'FLAWLESS_CLEARS_COUNT', threshold: 25 },
    reward: { tokens: 50, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'flawless_clears_100',
    name: 'Perfection',
    description: 'Gagner 100 combats sans aucune perte.',
    family: 'mastery',
    tier: 4,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'FLAWLESS_CLEARS_COUNT', threshold: 100 },
    reward: { tokens: 100, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'understaffed_clear_1',
    name: 'Surpassé en nombre',
    description: 'Gagner un combat en sous-effectif (moins de 3 personnages).',
    family: 'mastery',
    tier: 2,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'UNDERSTAFFED_CLEARS_COUNT', threshold: 1 },
    reward: { tokens: 20, dust: 100, xp: 50 },
  },
  {
    key: 'cards_max_level_1',
    name: 'Apogée',
    description:
      'Monter un personnage au niveau maximum (palier 6, niveau 60).',
    family: 'mastery',
    tier: 2,
    hidden: false,
    sortOrder: 5,
    criterion: { type: 'CARDS_AT_MAX_LEVEL', threshold: 1 },
    reward: { tokens: 20, dust: 100, xp: 50 },
  },
  {
    key: 'cards_max_level_5',
    name: 'Panthéon des champions',
    description: 'Monter 5 personnages au niveau maximum.',
    family: 'mastery',
    tier: 3,
    hidden: false,
    sortOrder: 6,
    criterion: { type: 'CARDS_AT_MAX_LEVEL', threshold: 5 },
    reward: { tokens: 50, dust: 250, xp: 0, cardRarity: 'RARE' },
  },

  // cachés
  {
    key: 'first_pull',
    name: 'Bienvenue',
    description: 'Réaliser votre tout premier tirage.',
    family: null,
    tier: 0,
    hidden: true,
    sortOrder: 0,
    criterion: { type: 'CUSTOM_EVENT', handlerKey: 'first_pull_ever' },
    reward: { tokens: 3, dust: 0, xp: 0 },
  },
  {
    key: 'rainbow_day',
    name: 'Arc-en-ciel',
    description:
      'Obtenir une carte commune, peu commune, rare et épique dans la même journée.',
    family: null,
    tier: 0,
    hidden: true,
    sortOrder: 0,
    criterion: { type: 'CUSTOM_EVENT', handlerKey: 'four_rarities_one_day' },
    reward: { tokens: 0, dust: 0, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'dust_hoarder',
    name: 'Pactole',
    description: 'Atteindre 10 000 de poussière.',
    family: null,
    tier: 0,
    hidden: true,
    sortOrder: 0,
    criterion: { type: 'CUSTOM_EVENT', handlerKey: 'dust_balance_10k' },
    reward: { tokens: 20, dust: 0, xp: 0 },
  },
]

export async function seedAchievements(tx: Tx) {
  for (const entry of ENTRIES) {
    const rewardData = {
      tokens: entry.reward.tokens,
      dust: entry.reward.dust,
      xp: entry.reward.xp,
      cardRarity: entry.reward.cardRarity ?? null,
    }
    await tx.achievement.upsert({
      where: { key: entry.key },
      create: {
        key: entry.key,
        name: entry.name,
        description: entry.description,
        family: entry.family,
        tier: entry.tier,
        hidden: entry.hidden,
        sortOrder: entry.sortOrder,
        isActive: true,
        criterion: entry.criterion,
        reward: { create: rewardData },
      },
      update: {
        name: entry.name,
        description: entry.description,
        family: entry.family,
        tier: entry.tier,
        hidden: entry.hidden,
        sortOrder: entry.sortOrder,
        isActive: true,
        criterion: entry.criterion,
        reward: { update: rewardData },
      },
    })
  }
}
