networks:
  proxy:
    name: proxy
    external: true

services:
  back:
    build:
      context: ../back
      dockerfile: deploy/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        MIRROR_URL: ${MIRROR_URL}
        NODE_VERSION: ${NODE_VERSION}
        NPM_VERSION: ${NPM_VERSION}
      target: app
    image: "${CONTAINER_REGISTRY_PREFIX}${APP_IMAGE_NAME}-back:${VERSION:-latest}"
    container_name: "${APP_IMAGE_NAME}-back"
    profiles:
      - backend
    healthcheck:
      test: node -e "require('http').get({hostname:'localhost', port:${PORT}, path:'/health', timeout:3000})"
      retries: 3
      timeout: 3s
      interval: 5s
    environment:
      - CORS_ORIGIN
      - DATABASE_URL
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - DISCORD_REDIRECT_URI
      - FRONT_URL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_REDIRECT_URI
      - HOST
      - JWT_REFRESH_SECRET
      - JWT_SECRET
      - LOG_LEVEL
      - MINIO_ACCESS_KEY
      - MINIO_BUCKET
      - MINIO_ENDPOINT
      - MINIO_SECRET_KEY
      - NODE_CLUSTER
      - NODE_ENV=production
      - NODE_TLS_REJECT_UNAUTHORIZED
      - PITY_THRESHOLD
      - PORT
      - REDIS_URL
      - TOKEN_MAX_STOCK
      - TOKEN_REGEN_INTERVAL_MINUTES
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_IMAGE_NAME}-back.rule=Host(`${TRAEFIK_BACK_HOST}`)"
      - "traefik.http.routers.${APP_IMAGE_NAME}-back.entrypoints=https"
      - "traefik.http.routers.${APP_IMAGE_NAME}-back.tls=true"
      - "traefik.http.routers.${APP_IMAGE_NAME}-back.tls.certresolver=ovh"
      - "traefik.http.services.${APP_IMAGE_NAME}-back.loadbalancer.server.port=${PORT}"
    networks:
      - proxy
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  front:
    build:
      context: ../front
      dockerfile: deploy/Dockerfile
      args:
        MIRROR_URL: ${MIRROR_URL}
        VITE_API_URL: ${VITE_API_URL}
        VITE_ENVIRONMENT: ${VITE_ENVIRONMENT}
        NODE_VERSION: ${NODE_VERSION}
        NPM_VERSION: ${NPM_VERSION}
    image: "${CONTAINER_REGISTRY_PREFIX}${APP_IMAGE_NAME}-front:${VERSION:-latest}"
    container_name: "${APP_IMAGE_NAME}-front"
    profiles:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${APP_IMAGE_NAME}-front.rule=Host(`${TRAEFIK_FRONT_HOST}`)"
      - "traefik.http.routers.${APP_IMAGE_NAME}-front.entrypoints=https"
      - "traefik.http.routers.${APP_IMAGE_NAME}-front.tls=true"
      - "traefik.http.routers.${APP_IMAGE_NAME}-front.tls.certresolver=ovh"
      - "traefik.http.services.${APP_IMAGE_NAME}-front.loadbalancer.server.port=80"
    networks:
      - proxy
    restart: unless-stopped

  postgres:
    container_name: "${APP_IMAGE_NAME}-postgres"
    image: postgres:16-alpine
    profiles:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      retries: 3
      timeout: 3s
      interval: 5s
    networks:
      - proxy
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: "${APP_IMAGE_NAME}-redis"
    image: redis:7-alpine
    profiles:
      - db
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 3s
      interval: 5s
    networks:
      - proxy
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres:
    driver: local
  redis_data:
    driver: local
