/**
 * Définitions des succès — 64 entrées.
 *
 * Vit sous `src/main/` et non dans `prisma/seed/` parce que du code de
 * PRODUCTION la consomme : le backfill de traductions au démarrage doit lire
 * ces libellés, et `npm run build` ne transpile que `src/main/`.
 * `prisma/seed/achievements.ts` n'y garde que l'écriture en base.
 */

import type { Prisma } from '../../../generated/client'

export interface AchievementDefinition {
  key: string
  /** nameEn/descriptionEn recopient le francais : la tache 8 traduira. */
  nameFr: string
  nameEn: string
  descriptionFr: string
  descriptionEn: string
  family: string | null
  tier: number
  hidden: boolean
  sortOrder: number
  criterion: Prisma.InputJsonValue
  reward: { tokens: number; dust: number; xp: number; cardRarity?: string }
}

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  // pulls
  {
    key: 'pulls_10',
    nameFr: 'Mise en jambes',
    nameEn: 'Mise en jambes',
    descriptionFr: 'Réaliser 10 tirages.',
    descriptionEn: 'Réaliser 10 tirages.',
    family: 'pulls',
    tier: 0,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'PULL_COUNT', threshold: 10 },
    reward: { tokens: 1, dust: 0, xp: 0 },
  },
  {
    key: 'pulls_100',
    nameFr: 'Habitué·e',
    nameEn: 'Habitué·e',
    descriptionFr: 'Réaliser 100 tirages.',
    descriptionEn: 'Réaliser 100 tirages.',
    family: 'pulls',
    tier: 1,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'PULL_COUNT', threshold: 100 },
    reward: { tokens: 1, dust: 30, xp: 0 },
  },
  {
    key: 'pulls_500',
    nameFr: 'Accro aux tirages',
    nameEn: 'Accro aux tirages',
    descriptionFr: 'Réaliser 500 tirages.',
    descriptionEn: 'Réaliser 500 tirages.',
    family: 'pulls',
    tier: 2,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'PULL_COUNT', threshold: 500 },
    reward: { tokens: 2, dust: 100, xp: 50 },
  },
  {
    key: 'pulls_1000',
    nameFr: 'Légende du gachapon',
    nameEn: 'Légende du gachapon',
    descriptionFr: 'Réaliser 1 000 tirages.',
    descriptionEn: 'Réaliser 1 000 tirages.',
    family: 'pulls',
    tier: 3,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'PULL_COUNT', threshold: 1000 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },

  // dust
  {
    key: 'dust_spent_500',
    nameFr: 'Premier investissement',
    nameEn: 'Premier investissement',
    descriptionFr: 'Dépenser 500 de poussière.',
    descriptionEn: 'Dépenser 500 de poussière.',
    family: 'dust',
    tier: 0,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'DUST_SPENT', threshold: 500 },
    reward: { tokens: 1, dust: 0, xp: 0 },
  },
  {
    key: 'dust_spent_5000',
    nameFr: 'Grand dépensier',
    nameEn: 'Grand dépensier',
    descriptionFr: 'Dépenser 5 000 de poussière.',
    descriptionEn: 'Dépenser 5 000 de poussière.',
    family: 'dust',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'DUST_SPENT', threshold: 5000 },
    reward: { tokens: 2, dust: 100, xp: 50 },
  },
  {
    key: 'cards_recycled_50',
    nameFr: 'Recycleur',
    nameEn: 'Recycleur',
    descriptionFr: 'Recycler 50 cartes.',
    descriptionEn: 'Recycler 50 cartes.',
    family: 'dust',
    tier: 1,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'CARDS_RECYCLED', threshold: 50 },
    reward: { tokens: 1, dust: 30, xp: 0 },
  },

  // collection_rarity
  {
    key: 'own_rare_10',
    nameFr: 'Chasseur de raretés',
    nameEn: 'Chasseur de raretés',
    descriptionFr: 'Posséder 10 cartes rares.',
    descriptionEn: 'Posséder 10 cartes rares.',
    family: 'collection_rarity',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'RARE', threshold: 10 },
    reward: { tokens: 1, dust: 30, xp: 0 },
  },
  {
    key: 'own_epic_5',
    nameFr: "Amateur d'épiques",
    nameEn: "Amateur d'épiques",
    descriptionFr: 'Posséder 5 cartes épiques.',
    descriptionEn: 'Posséder 5 cartes épiques.',
    family: 'collection_rarity',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'EPIC', threshold: 5 },
    reward: { tokens: 2, dust: 100, xp: 50 },
  },
  {
    key: 'own_legendary_1',
    nameFr: 'Première légende',
    nameEn: 'Première légende',
    descriptionFr: 'Posséder 1 carte légendaire.',
    descriptionEn: 'Posséder 1 carte légendaire.',
    family: 'collection_rarity',
    tier: 2,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'LEGENDARY', threshold: 1 },
    reward: { tokens: 2, dust: 100, xp: 50 },
  },
  {
    key: 'own_legendary_5',
    nameFr: 'Légende confirmée',
    nameEn: 'Légende confirmée',
    descriptionFr: 'Posséder 5 cartes légendaires.',
    descriptionEn: 'Posséder 5 cartes légendaires.',
    family: 'collection_rarity',
    tier: 3,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'LEGENDARY', threshold: 5 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_holographic_1',
    nameFr: 'Holographie',
    nameEn: 'Holographie',
    descriptionFr: 'Posséder 1 carte holographique.',
    descriptionEn: 'Posséder 1 carte holographique.',
    family: 'collection_rarity',
    tier: 2,
    hidden: false,
    sortOrder: 5,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'HOLOGRAPHIC',
      threshold: 1,
    },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },

  // collection_variants
  {
    key: 'own_brilliant_1',
    nameFr: 'Premier éclat',
    nameEn: 'Premier éclat',
    descriptionFr: 'Posséder 1 carte brillante.',
    descriptionEn: 'Posséder 1 carte brillante.',
    family: 'collection_variants',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'OWN_RARITY_COUNT', variant: 'BRILLIANT', threshold: 1 },
    reward: { tokens: 2, dust: 30, xp: 0 },
  },
  {
    key: 'own_brilliant_5',
    nameFr: 'Éclat persistant',
    nameEn: 'Éclat persistant',
    descriptionFr: 'Posséder 5 cartes brillantes.',
    descriptionEn: 'Posséder 5 cartes brillantes.',
    family: 'collection_variants',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'OWN_RARITY_COUNT', variant: 'BRILLIANT', threshold: 5 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'same_card_two_variants',
    nameFr: 'Double face',
    nameEn: 'Double face',
    descriptionFr: "Posséder 2 variantes d'une même carte.",
    descriptionEn: "Posséder 2 variantes d'une même carte.",
    family: 'collection_variants',
    tier: 2,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'CUSTOM_EVENT', handlerKey: 'same_card_two_variants' },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },

  // collection_complete
  {
    key: 'complete_common',
    nameFr: 'Collection commune',
    nameEn: 'Collection commune',
    descriptionFr: 'Posséder toutes les cartes communes.',
    descriptionEn: 'Posséder toutes les cartes communes.',
    family: 'collection_complete',
    tier: 3,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'COLLECTION_COMPLETE', scope: { rarity: 'COMMON' } },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'complete_1_set',
    nameFr: 'Set complet',
    nameEn: 'Set complet',
    descriptionFr: 'Compléter entièrement un set de cartes.',
    descriptionEn: 'Compléter entièrement un set de cartes.',
    family: 'collection_sets',
    tier: 3,
    hidden: false,
    sortOrder: 0,
    criterion: { type: 'SETS_COMPLETED', threshold: 1 },
    reward: { tokens: 5, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'complete_3_sets',
    nameFr: 'Collectionneur chevronné',
    nameEn: 'Collectionneur chevronné',
    descriptionFr: 'Compléter entièrement 3 sets de cartes.',
    descriptionEn: 'Compléter entièrement 3 sets de cartes.',
    family: 'collection_sets',
    tier: 4,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'SETS_COMPLETED', threshold: 3 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'complete_5_sets',
    nameFr: 'Maître collectionneur',
    nameEn: 'Maître collectionneur',
    descriptionFr: 'Compléter entièrement 5 sets de cartes.',
    descriptionEn: 'Compléter entièrement 5 sets de cartes.',
    family: 'collection_sets',
    tier: 5,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'SETS_COMPLETED', threshold: 5 },
    reward: { tokens: 40, dust: 1000, xp: 0, cardRarity: 'LEGENDARY' },
  },

  // streak
  {
    key: 'streak_30',
    nameFr: 'Mois complet',
    nameEn: 'Mois complet',
    descriptionFr: 'Atteindre 30 jours de série.',
    descriptionEn: 'Atteindre 30 jours de série.',
    family: 'streak',
    tier: 4,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'STREAK_REACHED', threshold: 30 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },

  // pulls (suite)
  {
    key: 'pulls_2500',
    nameFr: "Tireur d'élite",
    nameEn: "Tireur d'élite",
    descriptionFr: 'Réaliser 2 500 tirages.',
    descriptionEn: 'Réaliser 2 500 tirages.',
    family: 'pulls',
    tier: 4,
    hidden: false,
    sortOrder: 5,
    criterion: { type: 'PULL_COUNT', threshold: 2500 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'pulls_5000',
    nameFr: 'Divinité du gachapon',
    nameEn: 'Divinité du gachapon',
    descriptionFr: 'Réaliser 5 000 tirages.',
    descriptionEn: 'Réaliser 5 000 tirages.',
    family: 'pulls',
    tier: 5,
    hidden: false,
    sortOrder: 6,
    criterion: { type: 'PULL_COUNT', threshold: 5000 },
    reward: { tokens: 40, dust: 1000, xp: 0, cardRarity: 'LEGENDARY' },
  },

  // dust (suite)
  {
    key: 'dust_spent_50000',
    nameFr: 'Magnat de la poussière',
    nameEn: 'Magnat de la poussière',
    descriptionFr: 'Dépenser 50 000 de poussière.',
    descriptionEn: 'Dépenser 50 000 de poussière.',
    family: 'dust',
    tier: 4,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'DUST_SPENT', threshold: 50000 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'cards_recycled_250',
    nameFr: 'Grand recycleur',
    nameEn: 'Grand recycleur',
    descriptionFr: 'Recycler 250 cartes.',
    descriptionEn: 'Recycler 250 cartes.',
    family: 'dust',
    tier: 3,
    hidden: false,
    sortOrder: 5,
    criterion: { type: 'CARDS_RECYCLED', threshold: 250 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },

  // collection_rarity (suite)
  {
    key: 'own_rare_25',
    nameFr: 'Collectionneur de raretés',
    nameEn: 'Collectionneur de raretés',
    descriptionFr: 'Posséder 25 cartes rares.',
    descriptionEn: 'Posséder 25 cartes rares.',
    family: 'collection_rarity',
    tier: 2,
    hidden: false,
    sortOrder: 6,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'RARE', threshold: 25 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'own_rare_50',
    nameFr: 'Maître des raretés',
    nameEn: 'Maître des raretés',
    descriptionFr: 'Posséder 50 cartes rares.',
    descriptionEn: 'Posséder 50 cartes rares.',
    family: 'collection_rarity',
    tier: 3,
    hidden: false,
    sortOrder: 7,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'RARE', threshold: 50 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_epic_15',
    nameFr: "Amateur confirmé d'épiques",
    nameEn: "Amateur confirmé d'épiques",
    descriptionFr: 'Posséder 15 cartes épiques.',
    descriptionEn: 'Posséder 15 cartes épiques.',
    family: 'collection_rarity',
    tier: 3,
    hidden: false,
    sortOrder: 8,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'EPIC', threshold: 15 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_epic_30',
    nameFr: 'Maître des épiques',
    nameEn: 'Maître des épiques',
    descriptionFr: 'Posséder 30 cartes épiques.',
    descriptionEn: 'Posséder 30 cartes épiques.',
    family: 'collection_rarity',
    tier: 4,
    hidden: false,
    sortOrder: 9,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'EPIC', threshold: 30 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'own_legendary_10',
    nameFr: 'Panthéon',
    nameEn: 'Panthéon',
    descriptionFr: 'Posséder 10 cartes légendaires.',
    descriptionEn: 'Posséder 10 cartes légendaires.',
    family: 'collection_rarity',
    tier: 4,
    hidden: false,
    sortOrder: 10,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'LEGENDARY', threshold: 10 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'own_legendary_20',
    nameFr: 'Olympe',
    nameEn: 'Olympe',
    descriptionFr: 'Posséder 20 cartes légendaires.',
    descriptionEn: 'Posséder 20 cartes légendaires.',
    family: 'collection_rarity',
    tier: 5,
    hidden: false,
    sortOrder: 11,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'LEGENDARY', threshold: 20 },
    reward: { tokens: 40, dust: 1000, xp: 0, cardRarity: 'LEGENDARY' },
  },
  {
    key: 'own_holographic_3',
    nameFr: 'Reflets multiples',
    nameEn: 'Reflets multiples',
    descriptionFr: 'Posséder 3 cartes holographiques.',
    descriptionEn: 'Posséder 3 cartes holographiques.',
    family: 'collection_rarity',
    tier: 3,
    hidden: false,
    sortOrder: 12,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'HOLOGRAPHIC',
      threshold: 3,
    },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_holographic_10',
    nameFr: 'Prisme complet',
    nameEn: 'Prisme complet',
    descriptionFr: 'Posséder 10 cartes holographiques.',
    descriptionEn: 'Posséder 10 cartes holographiques.',
    family: 'collection_rarity',
    tier: 4,
    hidden: false,
    sortOrder: 13,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'HOLOGRAPHIC',
      threshold: 10,
    },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },

  // collection_variants (suite)
  {
    key: 'own_brilliant_15',
    nameFr: 'Éclat rayonnant',
    nameEn: 'Éclat rayonnant',
    descriptionFr: 'Posséder 15 cartes brillantes.',
    descriptionEn: 'Posséder 15 cartes brillantes.',
    family: 'collection_variants',
    tier: 3,
    hidden: false,
    sortOrder: 4,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'BRILLIANT',
      threshold: 15,
    },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_brilliant_30',
    nameFr: 'Éclat éternel',
    nameEn: 'Éclat éternel',
    descriptionFr: 'Posséder 30 cartes brillantes.',
    descriptionEn: 'Posséder 30 cartes brillantes.',
    family: 'collection_variants',
    tier: 4,
    hidden: false,
    sortOrder: 5,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'BRILLIANT',
      threshold: 30,
    },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },

  // collection_sets (suite)
  {
    key: 'complete_10_sets',
    nameFr: 'Grand maître collectionneur',
    nameEn: 'Grand maître collectionneur',
    descriptionFr: 'Compléter entièrement 10 sets de cartes.',
    descriptionEn: 'Compléter entièrement 10 sets de cartes.',
    family: 'collection_sets',
    tier: 5,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'SETS_COMPLETED', threshold: 10 },
    reward: { tokens: 60, dust: 1500, xp: 0, cardRarity: 'LEGENDARY' },
  },

  // streak (suite)
  {
    key: 'streak_60',
    nameFr: "Deux mois d'affilée",
    nameEn: "Deux mois d'affilée",
    descriptionFr: 'Atteindre 60 jours de série.',
    descriptionEn: 'Atteindre 60 jours de série.',
    family: 'streak',
    tier: 5,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'STREAK_REACHED', threshold: 60 },
    reward: { tokens: 40, dust: 1000, xp: 0, cardRarity: 'LEGENDARY' },
  },
  {
    key: 'streak_100',
    nameFr: 'Centenaire',
    nameEn: 'Centenaire',
    descriptionFr: 'Atteindre 100 jours de série.',
    descriptionEn: 'Atteindre 100 jours de série.',
    family: 'streak',
    tier: 5,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'STREAK_REACHED', threshold: 100 },
    reward: { tokens: 60, dust: 1500, xp: 0, cardRarity: 'LEGENDARY' },
  },

  // account
  {
    key: 'level_10',
    nameFr: 'Apprenti',
    nameEn: 'Apprenti',
    descriptionFr: 'Atteindre le niveau 10.',
    descriptionEn: 'Atteindre le niveau 10.',
    family: 'account',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'LEVEL_REACHED', threshold: 10 },
    reward: { tokens: 1, dust: 30, xp: 0 },
  },
  {
    key: 'level_25',
    nameFr: 'Vétéran',
    nameEn: 'Vétéran',
    descriptionFr: 'Atteindre le niveau 25.',
    descriptionEn: 'Atteindre le niveau 25.',
    family: 'account',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'LEVEL_REACHED', threshold: 25 },
    reward: { tokens: 2, dust: 100, xp: 50 },
  },
  {
    key: 'level_50',
    nameFr: 'Expert',
    nameEn: 'Expert',
    descriptionFr: 'Atteindre le niveau 50.',
    descriptionEn: 'Atteindre le niveau 50.',
    family: 'account',
    tier: 3,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'LEVEL_REACHED', threshold: 50 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'level_100',
    nameFr: 'Sommet',
    nameEn: 'Sommet',
    descriptionFr: 'Atteindre le niveau 100.',
    descriptionEn: 'Atteindre le niveau 100.',
    family: 'account',
    tier: 4,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'LEVEL_REACHED', threshold: 100 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },

  // campaign
  {
    key: 'stages_cleared_25',
    nameFr: 'Éclaireur',
    nameEn: 'Éclaireur',
    descriptionFr: 'Vaincre 25 étages de campagne.',
    descriptionEn: 'Vaincre 25 étages de campagne.',
    family: 'campaign',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'STAGES_CLEARED_COUNT', threshold: 25 },
    reward: { tokens: 2, dust: 30, xp: 0 },
  },
  {
    key: 'stages_cleared_50',
    nameFr: 'Conquérant',
    nameEn: 'Conquérant',
    descriptionFr: 'Vaincre 50 étages de campagne.',
    descriptionEn: 'Vaincre 50 étages de campagne.',
    family: 'campaign',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'STAGES_CLEARED_COUNT', threshold: 50 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'stages_cleared_100',
    nameFr: 'Général',
    nameEn: 'Général',
    descriptionFr: 'Vaincre 100 étages de campagne.',
    descriptionEn: 'Vaincre 100 étages de campagne.',
    family: 'campaign',
    tier: 3,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'STAGES_CLEARED_COUNT', threshold: 100 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'boss_defeats_5',
    nameFr: 'Tueur de boss',
    nameEn: 'Tueur de boss',
    descriptionFr: 'Vaincre 5 boss.',
    descriptionEn: 'Vaincre 5 boss.',
    family: 'campaign',
    tier: 1,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'BOSS_DEFEATS_COUNT', threshold: 5 },
    reward: { tokens: 2, dust: 30, xp: 0 },
  },
  {
    key: 'boss_defeats_10',
    nameFr: 'Fléau des boss',
    nameEn: 'Fléau des boss',
    descriptionFr: 'Vaincre 10 boss.',
    descriptionEn: 'Vaincre 10 boss.',
    family: 'campaign',
    tier: 2,
    hidden: false,
    sortOrder: 5,
    criterion: { type: 'BOSS_DEFEATS_COUNT', threshold: 10 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'boss_defeats_25',
    nameFr: 'Cauchemar des boss',
    nameEn: 'Cauchemar des boss',
    descriptionFr: 'Vaincre 25 boss.',
    descriptionEn: 'Vaincre 25 boss.',
    family: 'campaign',
    tier: 3,
    hidden: false,
    sortOrder: 6,
    criterion: { type: 'BOSS_DEFEATS_COUNT', threshold: 25 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'chapter_reached_2',
    nameFr: 'Nouvel horizon',
    nameEn: 'Nouvel horizon',
    descriptionFr: 'Atteindre le chapitre 2.',
    descriptionEn: 'Atteindre le chapitre 2.',
    family: 'campaign',
    tier: 1,
    hidden: false,
    sortOrder: 7,
    criterion: { type: 'CAMPAIGN_CHAPTER_REACHED', threshold: 2 },
    reward: { tokens: 2, dust: 30, xp: 0 },
  },
  {
    key: 'chapter_reached_3',
    nameFr: 'Terres lointaines',
    nameEn: 'Terres lointaines',
    descriptionFr: 'Atteindre le chapitre 3.',
    descriptionEn: 'Atteindre le chapitre 3.',
    family: 'campaign',
    tier: 2,
    hidden: false,
    sortOrder: 8,
    criterion: { type: 'CAMPAIGN_CHAPTER_REACHED', threshold: 3 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'chapter_reached_5',
    nameFr: 'Cristaux',
    nameEn: 'Cristaux',
    descriptionFr: 'Atteindre le chapitre 5.',
    descriptionEn: 'Atteindre le chapitre 5.',
    family: 'campaign',
    tier: 2,
    hidden: false,
    sortOrder: 9,
    criterion: { type: 'CAMPAIGN_CHAPTER_REACHED', threshold: 5 },
    reward: { tokens: 6, dust: 150, xp: 80 },
  },
  {
    key: 'chapter_reached_7',
    nameFr: 'Toundra',
    nameEn: 'Toundra',
    descriptionFr: 'Atteindre le chapitre 7.',
    descriptionEn: 'Atteindre le chapitre 7.',
    family: 'campaign',
    tier: 3,
    hidden: false,
    sortOrder: 10,
    criterion: { type: 'CAMPAIGN_CHAPTER_REACHED', threshold: 7 },
    reward: { tokens: 12, dust: 300, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'chapter_reached_9',
    nameFr: 'Au bout de la Faille',
    nameEn: 'Au bout de la Faille',
    descriptionFr: 'Atteindre le chapitre 9.',
    descriptionEn: 'Atteindre le chapitre 9.',
    family: 'campaign',
    tier: 4,
    hidden: false,
    sortOrder: 11,
    criterion: { type: 'CAMPAIGN_CHAPTER_REACHED', threshold: 9 },
    reward: { tokens: 25, dust: 600, xp: 0, cardRarity: 'EPIC' },
  },

  // mastery
  {
    key: 'flawless_clears_1',
    nameFr: 'Sans une égratignure',
    nameEn: 'Sans une égratignure',
    descriptionFr: 'Gagner un combat sans aucune perte.',
    descriptionEn: 'Gagner un combat sans aucune perte.',
    family: 'mastery',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'FLAWLESS_CLEARS_COUNT', threshold: 1 },
    reward: { tokens: 2, dust: 30, xp: 0 },
  },
  {
    key: 'flawless_clears_25',
    nameFr: 'Intouchable',
    nameEn: 'Intouchable',
    descriptionFr: 'Gagner 25 combats sans aucune perte.',
    descriptionEn: 'Gagner 25 combats sans aucune perte.',
    family: 'mastery',
    tier: 3,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'FLAWLESS_CLEARS_COUNT', threshold: 25 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'flawless_clears_100',
    nameFr: 'Perfection',
    nameEn: 'Perfection',
    descriptionFr: 'Gagner 100 combats sans aucune perte.',
    descriptionEn: 'Gagner 100 combats sans aucune perte.',
    family: 'mastery',
    tier: 4,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'FLAWLESS_CLEARS_COUNT', threshold: 100 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'understaffed_clear_1',
    nameFr: 'Surpassé en nombre',
    nameEn: 'Surpassé en nombre',
    descriptionFr:
      'Gagner un combat en sous-effectif (moins de 3 personnages).',
    descriptionEn:
      'Gagner un combat en sous-effectif (moins de 3 personnages).',
    family: 'mastery',
    tier: 2,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'UNDERSTAFFED_CLEARS_COUNT', threshold: 1 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'cards_max_level_1',
    nameFr: 'Apogée',
    nameEn: 'Apogée',
    descriptionFr:
      'Monter un personnage au niveau maximum (palier 7, niveau 70).',
    descriptionEn:
      'Monter un personnage au niveau maximum (palier 7, niveau 70).',
    family: 'mastery',
    tier: 2,
    hidden: false,
    sortOrder: 5,
    criterion: { type: 'CARDS_AT_MAX_LEVEL', threshold: 1 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'cards_max_level_5',
    nameFr: 'Panthéon des champions',
    nameEn: 'Panthéon des champions',
    descriptionFr: 'Monter 5 personnages au niveau maximum.',
    descriptionEn: 'Monter 5 personnages au niveau maximum.',
    family: 'mastery',
    tier: 3,
    hidden: false,
    sortOrder: 6,
    criterion: { type: 'CARDS_AT_MAX_LEVEL', threshold: 5 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },

  // cachés
  {
    key: 'first_pull',
    nameFr: 'Bienvenue',
    nameEn: 'Bienvenue',
    descriptionFr: 'Réaliser votre tout premier tirage.',
    descriptionEn: 'Réaliser votre tout premier tirage.',
    family: null,
    tier: 0,
    hidden: true,
    sortOrder: 0,
    criterion: { type: 'CUSTOM_EVENT', handlerKey: 'first_pull_ever' },
    reward: { tokens: 1, dust: 0, xp: 0 },
  },
  {
    key: 'rainbow_day',
    nameFr: 'Arc-en-ciel',
    nameEn: 'Arc-en-ciel',
    descriptionFr:
      'Obtenir une carte commune, peu commune, rare et épique dans la même journée.',
    descriptionEn:
      'Obtenir une carte commune, peu commune, rare et épique dans la même journée.',
    family: null,
    tier: 0,
    hidden: true,
    sortOrder: 0,
    criterion: { type: 'CUSTOM_EVENT', handlerKey: 'four_rarities_one_day' },
    reward: { tokens: 0, dust: 0, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'dust_hoarder',
    nameFr: 'Pactole',
    nameEn: 'Pactole',
    descriptionFr: 'Atteindre 10 000 de poussière.',
    descriptionEn: 'Atteindre 10 000 de poussière.',
    family: null,
    tier: 0,
    hidden: true,
    sortOrder: 0,
    criterion: { type: 'CUSTOM_EVENT', handlerKey: 'dust_balance_10k' },
    reward: { tokens: 4, dust: 0, xp: 0 },
  },
]
