/**
 * Définitions des succès — 64 entrées.
 *
 * Vit sous `src/main/` et non dans `prisma/seed/` parce que du code de
 * PRODUCTION la consomme : le backfill de traductions au démarrage doit lire
 * ces libellés, et `npm run build` ne transpile que `src/main/`.
 * `prisma/seed/achievements.ts` n'y garde que l'écriture en base.
 */

import type { Prisma } from '../../../generated/client'

export interface AchievementDefinition {
  key: string
  nameFr: string
  nameEn: string
  descriptionFr: string
  descriptionEn: string
  family: string | null
  tier: number
  hidden: boolean
  sortOrder: number
  criterion: Prisma.InputJsonValue
  reward: { tokens: number; dust: number; xp: number; cardRarity?: string }
}

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  // pulls
  {
    key: 'pulls_10',
    nameFr: 'Mise en jambes',
    nameEn: 'Warming Up',
    descriptionFr: 'Réaliser 10 tirages.',
    descriptionEn: 'Complete 10 pulls.',
    family: 'pulls',
    tier: 0,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'PULL_COUNT', threshold: 10 },
    reward: { tokens: 1, dust: 0, xp: 0 },
  },
  {
    key: 'pulls_100',
    nameFr: 'Habitué·e',
    nameEn: 'The Regular',
    descriptionFr: 'Réaliser 100 tirages.',
    descriptionEn: 'Complete 100 pulls.',
    family: 'pulls',
    tier: 1,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'PULL_COUNT', threshold: 100 },
    reward: { tokens: 1, dust: 30, xp: 0 },
  },
  {
    key: 'pulls_500',
    nameFr: 'Accro aux tirages',
    nameEn: 'Pull Addict',
    descriptionFr: 'Réaliser 500 tirages.',
    descriptionEn: 'Complete 500 pulls.',
    family: 'pulls',
    tier: 2,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'PULL_COUNT', threshold: 500 },
    reward: { tokens: 2, dust: 100, xp: 50 },
  },
  {
    key: 'pulls_1000',
    nameFr: 'Légende du gachapon',
    nameEn: 'Gachapon Legend',
    descriptionFr: 'Réaliser 1 000 tirages.',
    descriptionEn: 'Complete 1,000 pulls.',
    family: 'pulls',
    tier: 3,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'PULL_COUNT', threshold: 1000 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },

  // dust
  {
    key: 'dust_spent_500',
    nameFr: 'Premier investissement',
    nameEn: 'First Investment',
    descriptionFr: 'Dépenser 500 de poussière.',
    descriptionEn: 'Spend 500 dust.',
    family: 'dust',
    tier: 0,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'DUST_SPENT', threshold: 500 },
    reward: { tokens: 1, dust: 0, xp: 0 },
  },
  {
    key: 'dust_spent_5000',
    nameFr: 'Grand dépensier',
    nameEn: 'Big Spender',
    descriptionFr: 'Dépenser 5 000 de poussière.',
    descriptionEn: 'Spend 5,000 dust.',
    family: 'dust',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'DUST_SPENT', threshold: 5000 },
    reward: { tokens: 2, dust: 100, xp: 50 },
  },
  {
    key: 'cards_recycled_50',
    nameFr: 'Recycleur',
    nameEn: 'Recycler',
    descriptionFr: 'Recycler 50 cartes.',
    descriptionEn: 'Recycle 50 cards.',
    family: 'dust',
    tier: 1,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'CARDS_RECYCLED', threshold: 50 },
    reward: { tokens: 1, dust: 30, xp: 0 },
  },

  // collection_rarity
  {
    key: 'own_rare_10',
    nameFr: 'Chasseur de raretés',
    nameEn: 'Rarity Hunter',
    descriptionFr: 'Posséder 10 cartes rares.',
    descriptionEn: 'Own 10 rare cards.',
    family: 'collection_rarity',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'RARE', threshold: 10 },
    reward: { tokens: 1, dust: 30, xp: 0 },
  },
  {
    key: 'own_epic_5',
    nameFr: "Amateur d'épiques",
    nameEn: 'Epic Enthusiast',
    descriptionFr: 'Posséder 5 cartes épiques.',
    descriptionEn: 'Own 5 epic cards.',
    family: 'collection_rarity',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'EPIC', threshold: 5 },
    reward: { tokens: 2, dust: 100, xp: 50 },
  },
  {
    key: 'own_legendary_1',
    nameFr: 'Première légende',
    nameEn: 'First Legend',
    descriptionFr: 'Posséder 1 carte légendaire.',
    descriptionEn: 'Own 1 legendary card.',
    family: 'collection_rarity',
    tier: 2,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'LEGENDARY', threshold: 1 },
    reward: { tokens: 2, dust: 100, xp: 50 },
  },
  {
    key: 'own_legendary_5',
    nameFr: 'Légende confirmée',
    nameEn: 'Legend Confirmed',
    descriptionFr: 'Posséder 5 cartes légendaires.',
    descriptionEn: 'Own 5 legendary cards.',
    family: 'collection_rarity',
    tier: 3,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'LEGENDARY', threshold: 5 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_holographic_1',
    nameFr: 'Holographie',
    nameEn: 'Holography',
    descriptionFr: 'Posséder 1 carte holographique.',
    descriptionEn: 'Own 1 holographic card.',
    family: 'collection_rarity',
    tier: 2,
    hidden: false,
    sortOrder: 5,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'HOLOGRAPHIC',
      threshold: 1,
    },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },

  // collection_variants
  {
    key: 'own_brilliant_1',
    nameFr: 'Premier éclat',
    nameEn: 'First Sparkle',
    descriptionFr: 'Posséder 1 carte brillante.',
    descriptionEn: 'Own 1 brilliant card.',
    family: 'collection_variants',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'OWN_RARITY_COUNT', variant: 'BRILLIANT', threshold: 1 },
    reward: { tokens: 2, dust: 30, xp: 0 },
  },
  {
    key: 'own_brilliant_5',
    nameFr: 'Éclat persistant',
    nameEn: 'Lasting Sparkle',
    descriptionFr: 'Posséder 5 cartes brillantes.',
    descriptionEn: 'Own 5 brilliant cards.',
    family: 'collection_variants',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'OWN_RARITY_COUNT', variant: 'BRILLIANT', threshold: 5 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'same_card_two_variants',
    nameFr: 'Double face',
    nameEn: 'Double Take',
    descriptionFr: "Posséder 2 variantes d'une même carte.",
    descriptionEn: 'Own 2 variants of the same card.',
    family: 'collection_variants',
    tier: 2,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'CUSTOM_EVENT', handlerKey: 'same_card_two_variants' },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },

  // collection_complete
  {
    key: 'complete_common',
    nameFr: 'Collection commune',
    nameEn: 'Common Collection',
    descriptionFr: 'Posséder toutes les cartes communes.',
    descriptionEn: 'Own every common card.',
    family: 'collection_complete',
    tier: 3,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'COLLECTION_COMPLETE', scope: { rarity: 'COMMON' } },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'complete_1_set',
    nameFr: 'Set complet',
    nameEn: 'Complete Set',
    descriptionFr: 'Compléter entièrement un set de cartes.',
    descriptionEn: 'Fully complete a card set.',
    family: 'collection_sets',
    tier: 3,
    hidden: false,
    sortOrder: 0,
    criterion: { type: 'SETS_COMPLETED', threshold: 1 },
    reward: { tokens: 5, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'complete_3_sets',
    nameFr: 'Collectionneur chevronné',
    nameEn: 'Seasoned Collector',
    descriptionFr: 'Compléter entièrement 3 sets de cartes.',
    descriptionEn: 'Fully complete 3 card sets.',
    family: 'collection_sets',
    tier: 4,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'SETS_COMPLETED', threshold: 3 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'complete_5_sets',
    nameFr: 'Maître collectionneur',
    nameEn: 'Master Collector',
    descriptionFr: 'Compléter entièrement 5 sets de cartes.',
    descriptionEn: 'Fully complete 5 card sets.',
    family: 'collection_sets',
    tier: 5,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'SETS_COMPLETED', threshold: 5 },
    reward: { tokens: 40, dust: 1000, xp: 0, cardRarity: 'LEGENDARY' },
  },

  // streak
  {
    key: 'streak_30',
    nameFr: 'Mois complet',
    nameEn: 'Full Month',
    descriptionFr: 'Atteindre 30 jours de série.',
    descriptionEn: 'Reach a 30-day streak.',
    family: 'streak',
    tier: 4,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'STREAK_REACHED', threshold: 30 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },

  // pulls (suite)
  {
    key: 'pulls_2500',
    nameFr: "Tireur d'élite",
    nameEn: 'Sharpshooter',
    descriptionFr: 'Réaliser 2 500 tirages.',
    descriptionEn: 'Complete 2,500 pulls.',
    family: 'pulls',
    tier: 4,
    hidden: false,
    sortOrder: 5,
    criterion: { type: 'PULL_COUNT', threshold: 2500 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'pulls_5000',
    nameFr: 'Divinité du gachapon',
    nameEn: 'Gachapon Deity',
    descriptionFr: 'Réaliser 5 000 tirages.',
    descriptionEn: 'Complete 5,000 pulls.',
    family: 'pulls',
    tier: 5,
    hidden: false,
    sortOrder: 6,
    criterion: { type: 'PULL_COUNT', threshold: 5000 },
    reward: { tokens: 40, dust: 1000, xp: 0, cardRarity: 'LEGENDARY' },
  },

  // dust (suite)
  {
    key: 'dust_spent_50000',
    nameFr: 'Magnat de la poussière',
    nameEn: 'Dust Magnate',
    descriptionFr: 'Dépenser 50 000 de poussière.',
    descriptionEn: 'Spend 50,000 dust.',
    family: 'dust',
    tier: 4,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'DUST_SPENT', threshold: 50000 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'cards_recycled_250',
    nameFr: 'Grand recycleur',
    nameEn: 'Master Recycler',
    descriptionFr: 'Recycler 250 cartes.',
    descriptionEn: 'Recycle 250 cards.',
    family: 'dust',
    tier: 3,
    hidden: false,
    sortOrder: 5,
    criterion: { type: 'CARDS_RECYCLED', threshold: 250 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },

  // collection_rarity (suite)
  {
    key: 'own_rare_25',
    nameFr: 'Collectionneur de raretés',
    nameEn: 'Rarity Collector',
    descriptionFr: 'Posséder 25 cartes rares.',
    descriptionEn: 'Own 25 rare cards.',
    family: 'collection_rarity',
    tier: 2,
    hidden: false,
    sortOrder: 6,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'RARE', threshold: 25 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'own_rare_50',
    nameFr: 'Maître des raretés',
    nameEn: 'Rarity Master',
    descriptionFr: 'Posséder 50 cartes rares.',
    descriptionEn: 'Own 50 rare cards.',
    family: 'collection_rarity',
    tier: 3,
    hidden: false,
    sortOrder: 7,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'RARE', threshold: 50 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_epic_15',
    nameFr: "Amateur confirmé d'épiques",
    nameEn: 'Seasoned Epic Enthusiast',
    descriptionFr: 'Posséder 15 cartes épiques.',
    descriptionEn: 'Own 15 epic cards.',
    family: 'collection_rarity',
    tier: 3,
    hidden: false,
    sortOrder: 8,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'EPIC', threshold: 15 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_epic_30',
    nameFr: 'Maître des épiques',
    nameEn: 'Epic Master',
    descriptionFr: 'Posséder 30 cartes épiques.',
    descriptionEn: 'Own 30 epic cards.',
    family: 'collection_rarity',
    tier: 4,
    hidden: false,
    sortOrder: 9,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'EPIC', threshold: 30 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'own_legendary_10',
    nameFr: 'Panthéon',
    nameEn: 'Pantheon',
    descriptionFr: 'Posséder 10 cartes légendaires.',
    descriptionEn: 'Own 10 legendary cards.',
    family: 'collection_rarity',
    tier: 4,
    hidden: false,
    sortOrder: 10,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'LEGENDARY', threshold: 10 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'own_legendary_20',
    nameFr: 'Olympe',
    nameEn: 'Olympus',
    descriptionFr: 'Posséder 20 cartes légendaires.',
    descriptionEn: 'Own 20 legendary cards.',
    family: 'collection_rarity',
    tier: 5,
    hidden: false,
    sortOrder: 11,
    criterion: { type: 'OWN_RARITY_COUNT', rarity: 'LEGENDARY', threshold: 20 },
    reward: { tokens: 40, dust: 1000, xp: 0, cardRarity: 'LEGENDARY' },
  },
  {
    key: 'own_holographic_3',
    nameFr: 'Reflets multiples',
    nameEn: 'Multiple Reflections',
    descriptionFr: 'Posséder 3 cartes holographiques.',
    descriptionEn: 'Own 3 holographic cards.',
    family: 'collection_rarity',
    tier: 3,
    hidden: false,
    sortOrder: 12,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'HOLOGRAPHIC',
      threshold: 3,
    },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_holographic_10',
    nameFr: 'Prisme complet',
    nameEn: 'Full Prism',
    descriptionFr: 'Posséder 10 cartes holographiques.',
    descriptionEn: 'Own 10 holographic cards.',
    family: 'collection_rarity',
    tier: 4,
    hidden: false,
    sortOrder: 13,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'HOLOGRAPHIC',
      threshold: 10,
    },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },

  // collection_variants (suite)
  {
    key: 'own_brilliant_15',
    nameFr: 'Éclat rayonnant',
    nameEn: 'Radiant Sparkle',
    descriptionFr: 'Posséder 15 cartes brillantes.',
    descriptionEn: 'Own 15 brilliant cards.',
    family: 'collection_variants',
    tier: 3,
    hidden: false,
    sortOrder: 4,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'BRILLIANT',
      threshold: 15,
    },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'own_brilliant_30',
    nameFr: 'Éclat éternel',
    nameEn: 'Eternal Sparkle',
    descriptionFr: 'Posséder 30 cartes brillantes.',
    descriptionEn: 'Own 30 brilliant cards.',
    family: 'collection_variants',
    tier: 4,
    hidden: false,
    sortOrder: 5,
    criterion: {
      type: 'OWN_RARITY_COUNT',
      variant: 'BRILLIANT',
      threshold: 30,
    },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },

  // collection_sets (suite)
  {
    key: 'complete_10_sets',
    nameFr: 'Grand maître collectionneur',
    nameEn: 'Grand Master Collector',
    descriptionFr: 'Compléter entièrement 10 sets de cartes.',
    descriptionEn: 'Fully complete 10 card sets.',
    family: 'collection_sets',
    tier: 5,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'SETS_COMPLETED', threshold: 10 },
    reward: { tokens: 60, dust: 1500, xp: 0, cardRarity: 'LEGENDARY' },
  },

  // streak (suite)
  {
    key: 'streak_60',
    nameFr: "Deux mois d'affilée",
    nameEn: 'Two Months Straight',
    descriptionFr: 'Atteindre 60 jours de série.',
    descriptionEn: 'Reach a 60-day streak.',
    family: 'streak',
    tier: 5,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'STREAK_REACHED', threshold: 60 },
    reward: { tokens: 40, dust: 1000, xp: 0, cardRarity: 'LEGENDARY' },
  },
  {
    key: 'streak_100',
    nameFr: 'Centenaire',
    nameEn: 'Centenarian',
    descriptionFr: 'Atteindre 100 jours de série.',
    descriptionEn: 'Reach a 100-day streak.',
    family: 'streak',
    tier: 5,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'STREAK_REACHED', threshold: 100 },
    reward: { tokens: 60, dust: 1500, xp: 0, cardRarity: 'LEGENDARY' },
  },

  // account
  {
    key: 'level_10',
    nameFr: 'Apprenti',
    nameEn: 'Apprentice',
    descriptionFr: 'Atteindre le niveau 10.',
    descriptionEn: 'Reach level 10.',
    family: 'account',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'LEVEL_REACHED', threshold: 10 },
    reward: { tokens: 1, dust: 30, xp: 0 },
  },
  {
    key: 'level_25',
    nameFr: 'Vétéran',
    nameEn: 'Veteran',
    descriptionFr: 'Atteindre le niveau 25.',
    descriptionEn: 'Reach level 25.',
    family: 'account',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'LEVEL_REACHED', threshold: 25 },
    reward: { tokens: 2, dust: 100, xp: 50 },
  },
  {
    key: 'level_50',
    nameFr: 'Expert',
    nameEn: 'Expert',
    descriptionFr: 'Atteindre le niveau 50.',
    descriptionEn: 'Reach level 50.',
    family: 'account',
    tier: 3,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'LEVEL_REACHED', threshold: 50 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'level_100',
    nameFr: 'Sommet',
    nameEn: 'Summit',
    descriptionFr: 'Atteindre le niveau 100.',
    descriptionEn: 'Reach level 100.',
    family: 'account',
    tier: 4,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'LEVEL_REACHED', threshold: 100 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },

  // campaign
  {
    key: 'stages_cleared_25',
    nameFr: 'Éclaireur',
    nameEn: 'Scout',
    descriptionFr: 'Vaincre 25 étages de campagne.',
    descriptionEn: 'Clear 25 campaign stages.',
    family: 'campaign',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'STAGES_CLEARED_COUNT', threshold: 25 },
    reward: { tokens: 2, dust: 30, xp: 0 },
  },
  {
    key: 'stages_cleared_50',
    nameFr: 'Conquérant',
    nameEn: 'Conqueror',
    descriptionFr: 'Vaincre 50 étages de campagne.',
    descriptionEn: 'Clear 50 campaign stages.',
    family: 'campaign',
    tier: 2,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'STAGES_CLEARED_COUNT', threshold: 50 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'stages_cleared_100',
    nameFr: 'Général',
    nameEn: 'General',
    descriptionFr: 'Vaincre 100 étages de campagne.',
    descriptionEn: 'Clear 100 campaign stages.',
    family: 'campaign',
    tier: 3,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'STAGES_CLEARED_COUNT', threshold: 100 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'boss_defeats_5',
    nameFr: 'Tueur de boss',
    nameEn: 'Boss Slayer',
    descriptionFr: 'Vaincre 5 boss.',
    descriptionEn: 'Defeat 5 bosses.',
    family: 'campaign',
    tier: 1,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'BOSS_DEFEATS_COUNT', threshold: 5 },
    reward: { tokens: 2, dust: 30, xp: 0 },
  },
  {
    key: 'boss_defeats_10',
    nameFr: 'Fléau des boss',
    nameEn: 'Bane of Bosses',
    descriptionFr: 'Vaincre 10 boss.',
    descriptionEn: 'Defeat 10 bosses.',
    family: 'campaign',
    tier: 2,
    hidden: false,
    sortOrder: 5,
    criterion: { type: 'BOSS_DEFEATS_COUNT', threshold: 10 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'boss_defeats_25',
    nameFr: 'Cauchemar des boss',
    nameEn: 'Nightmare of Bosses',
    descriptionFr: 'Vaincre 25 boss.',
    descriptionEn: 'Defeat 25 bosses.',
    family: 'campaign',
    tier: 3,
    hidden: false,
    sortOrder: 6,
    criterion: { type: 'BOSS_DEFEATS_COUNT', threshold: 25 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'chapter_reached_2',
    nameFr: 'Nouvel horizon',
    nameEn: 'New Horizon',
    descriptionFr: 'Atteindre le chapitre 2.',
    descriptionEn: 'Reach chapter 2.',
    family: 'campaign',
    tier: 1,
    hidden: false,
    sortOrder: 7,
    criterion: { type: 'CAMPAIGN_CHAPTER_REACHED', threshold: 2 },
    reward: { tokens: 2, dust: 30, xp: 0 },
  },
  {
    key: 'chapter_reached_3',
    nameFr: 'Terres lointaines',
    nameEn: 'Distant Lands',
    descriptionFr: 'Atteindre le chapitre 3.',
    descriptionEn: 'Reach chapter 3.',
    family: 'campaign',
    tier: 2,
    hidden: false,
    sortOrder: 8,
    criterion: { type: 'CAMPAIGN_CHAPTER_REACHED', threshold: 3 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'chapter_reached_5',
    nameFr: 'Cristaux',
    nameEn: 'Crystals',
    descriptionFr: 'Atteindre le chapitre 5.',
    descriptionEn: 'Reach chapter 5.',
    family: 'campaign',
    tier: 2,
    hidden: false,
    sortOrder: 9,
    criterion: { type: 'CAMPAIGN_CHAPTER_REACHED', threshold: 5 },
    reward: { tokens: 6, dust: 150, xp: 80 },
  },
  {
    key: 'chapter_reached_7',
    nameFr: 'Toundra',
    nameEn: 'Tundra',
    descriptionFr: 'Atteindre le chapitre 7.',
    descriptionEn: 'Reach chapter 7.',
    family: 'campaign',
    tier: 3,
    hidden: false,
    sortOrder: 10,
    criterion: { type: 'CAMPAIGN_CHAPTER_REACHED', threshold: 7 },
    reward: { tokens: 12, dust: 300, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'chapter_reached_9',
    nameFr: 'Au bout de la Faille',
    nameEn: 'The Edge of the Rift',
    descriptionFr: 'Atteindre le chapitre 9.',
    descriptionEn: 'Reach chapter 9.',
    family: 'campaign',
    tier: 4,
    hidden: false,
    sortOrder: 11,
    criterion: { type: 'CAMPAIGN_CHAPTER_REACHED', threshold: 9 },
    reward: { tokens: 25, dust: 600, xp: 0, cardRarity: 'EPIC' },
  },

  // mastery
  {
    key: 'flawless_clears_1',
    nameFr: 'Sans une égratignure',
    nameEn: 'Without a Scratch',
    descriptionFr: 'Gagner un combat sans aucune perte.',
    descriptionEn: 'Win a battle without losing a single card.',
    family: 'mastery',
    tier: 1,
    hidden: false,
    sortOrder: 1,
    criterion: { type: 'FLAWLESS_CLEARS_COUNT', threshold: 1 },
    reward: { tokens: 2, dust: 30, xp: 0 },
  },
  {
    key: 'flawless_clears_25',
    nameFr: 'Intouchable',
    nameEn: 'Untouchable',
    descriptionFr: 'Gagner 25 combats sans aucune perte.',
    descriptionEn: 'Win 25 battles without losing a single card.',
    family: 'mastery',
    tier: 3,
    hidden: false,
    sortOrder: 2,
    criterion: { type: 'FLAWLESS_CLEARS_COUNT', threshold: 25 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'flawless_clears_100',
    nameFr: 'Perfection',
    nameEn: 'Perfection',
    descriptionFr: 'Gagner 100 combats sans aucune perte.',
    descriptionEn: 'Win 100 battles without losing a single card.',
    family: 'mastery',
    tier: 4,
    hidden: false,
    sortOrder: 3,
    criterion: { type: 'FLAWLESS_CLEARS_COUNT', threshold: 100 },
    reward: { tokens: 20, dust: 500, xp: 0, cardRarity: 'EPIC' },
  },
  {
    key: 'understaffed_clear_1',
    nameFr: 'Surpassé en nombre',
    nameEn: 'Outnumbered',
    descriptionFr:
      'Gagner un combat en sous-effectif (moins de 3 personnages).',
    descriptionEn: 'Win a battle undermanned (fewer than 3 characters).',
    family: 'mastery',
    tier: 2,
    hidden: false,
    sortOrder: 4,
    criterion: { type: 'UNDERSTAFFED_CLEARS_COUNT', threshold: 1 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'cards_max_level_1',
    nameFr: 'Apogée',
    nameEn: 'Apex',
    descriptionFr:
      'Monter un personnage au niveau maximum (palier 7, niveau 70).',
    descriptionEn: 'Level a character to the maximum (palier 7, level 70).',
    family: 'mastery',
    tier: 2,
    hidden: false,
    sortOrder: 5,
    criterion: { type: 'CARDS_AT_MAX_LEVEL', threshold: 1 },
    reward: { tokens: 4, dust: 100, xp: 50 },
  },
  {
    key: 'cards_max_level_5',
    nameFr: 'Panthéon des champions',
    nameEn: 'Pantheon of Champions',
    descriptionFr: 'Monter 5 personnages au niveau maximum.',
    descriptionEn: 'Level 5 characters to the maximum.',
    family: 'mastery',
    tier: 3,
    hidden: false,
    sortOrder: 6,
    criterion: { type: 'CARDS_AT_MAX_LEVEL', threshold: 5 },
    reward: { tokens: 10, dust: 250, xp: 0, cardRarity: 'RARE' },
  },

  // cachés
  {
    key: 'first_pull',
    nameFr: 'Bienvenue',
    nameEn: 'Welcome',
    descriptionFr: 'Réaliser votre tout premier tirage.',
    descriptionEn: 'Complete your very first pull.',
    family: null,
    tier: 0,
    hidden: true,
    sortOrder: 0,
    criterion: { type: 'CUSTOM_EVENT', handlerKey: 'first_pull_ever' },
    reward: { tokens: 1, dust: 0, xp: 0 },
  },
  {
    key: 'rainbow_day',
    nameFr: 'Arc-en-ciel',
    nameEn: 'Rainbow',
    descriptionFr:
      'Obtenir une carte commune, peu commune, rare et épique dans la même journée.',
    descriptionEn:
      'Get a common, uncommon, rare, and epic card on the same day.',
    family: null,
    tier: 0,
    hidden: true,
    sortOrder: 0,
    criterion: { type: 'CUSTOM_EVENT', handlerKey: 'four_rarities_one_day' },
    reward: { tokens: 0, dust: 0, xp: 0, cardRarity: 'RARE' },
  },
  {
    key: 'dust_hoarder',
    nameFr: 'Pactole',
    nameEn: 'Jackpot',
    descriptionFr: 'Atteindre 10 000 de poussière.',
    descriptionEn: 'Reach 10,000 dust.',
    family: null,
    tier: 0,
    hidden: true,
    sortOrder: 0,
    criterion: { type: 'CUSTOM_EVENT', handlerKey: 'dust_balance_10k' },
    reward: { tokens: 4, dust: 0, xp: 0 },
  },
]
