/**
 * Traductions des 17 familles de cartes importées par
 * `scripts/import-cards/import-cards.mjs` (toutes sauf les Humains, qui
 * vivent dans `cards.definitions.ts` avec leurs stats).
 *
 * Deux lecteurs :
 *  - `ContentTranslationsBootstrap`, au démarrage, qui pose `nameEn` sur les
 *    cartes déjà en base (rapprochées par le code de leur clé d'image) ;
 *  - l'import lui-même, qui crée les nouvelles cartes directement bilingues.
 *    Il charge ce fichier .ts tel quel (type stripping de Node) : d'où
 *    l'absence de tout import et de toute syntaxe non effaçable ici.
 *
 * Règle, la même que pour les Humains : un prénom reste tel quel, son
 * épithète se traduit. « Fougère » ou « Givrebise » sont des prénoms.
 *
 * `nameFr` / `descriptionFr` recopient `cards-data.json` et `families.json` :
 * `imported-cards-translations.test.ts` vérifie qu'ils ne divergent pas.
 */

export type ImportedCardSetText = {
  folder: string
  nameFr: string
  nameEn: string
  descriptionFr: string
  descriptionEn: string
}

export const IMPORTED_CARD_SETS: readonly ImportedCardSetText[] = [
  {
    folder: 'goblins',
    nameFr: 'Gobelins',
    nameEn: 'Goblins',
    descriptionFr:
      "Petits, sales, innombrables : ce qu'ils n'ont pas en force, ils l'ont en embuscades.",
    descriptionEn:
      'Small, filthy, countless: what they lack in strength, they make up for in ambushes.',
  },
  {
    folder: 'elves',
    nameFr: 'Elfes',
    nameEn: 'Elves',
    descriptionFr:
      'Arcs anciens et rancunes tenaces : la sylve tue de loin, et sans se presser.',
    descriptionEn:
      'Ancient bows and long grudges: the forest kills from afar, and takes its time.',
  },
  {
    folder: 'orcs',
    nameFr: 'Orcs',
    nameEn: 'Orcs',
    descriptionFr:
      "Ni finesse ni repli : les clans avancent tant qu'il reste un ennemi debout.",
    descriptionEn:
      'No finesse, no retreat: the clans march on as long as one enemy still stands.',
  },
  {
    folder: 'demons',
    nameFr: 'Démons',
    nameEn: 'Demons',
    descriptionFr:
      "Toute puissance se paie : ils accordent la victoire maintenant et présentent l'addition après.",
    descriptionEn:
      'All power comes at a price: they grant victory now and send the bill later.',
  },
  {
    folder: 'angels',
    nameFr: 'Anges',
    nameEn: 'Angels',
    descriptionFr:
      'Bannières de lumière et jugement sans appel : ils relèvent les leurs et brûlent le reste.',
    descriptionEn:
      'Banners of light and judgment without appeal: they raise their own and burn the rest.',
  },
  {
    folder: 'dragons',
    nameFr: 'Dragons',
    nameEn: 'Dragons',
    descriptionFr:
      "Écailles, souffle et trésor : les plus vieux prédateurs du monde n'ont jamais eu besoin d'alliés.",
    descriptionEn:
      "Scales, breath and hoard: the world's oldest predators never needed allies.",
  },
  {
    folder: 'dwarfs',
    nameFr: 'Nains',
    nameEn: 'Dwarves',
    descriptionFr:
      'Sous la montagne on forge, on encaisse et on ne recule pas : la roche a déteint sur eux.',
    descriptionEn:
      'Under the mountain they forge, they endure and they never back down: the rock has rubbed off on them.',
  },
  {
    folder: 'undeads',
    nameFr: 'Morts-vivants',
    nameEn: 'Undead',
    descriptionFr:
      "L'armée qui ne compte pas ses pertes : ce qui tombe se relève au tour suivant.",
    descriptionEn:
      'The army that never counts its losses: whatever falls rises again next turn.',
  },
  {
    folder: 'puazis',
    nameFr: 'Puazi',
    nameEn: 'Puazi',
    descriptionFr:
      "Peau d'ambre et cheveux d'écume : un peuple venu d'ailleurs, ses lances rituelles et sa reine.",
    descriptionEn:
      'Amber skin and sea-foam hair: a people from elsewhere, with their ritual spears and their queen.',
  },
  {
    folder: 'mermaids',
    nameFr: 'Sirènes',
    nameEn: 'Sirens',
    descriptionFr:
      "Récifs, courants et chants : on ne les entend qu'une fois, et c'est déjà trop tard.",
    descriptionEn:
      'Reefs, currents and songs: you only hear them once, and by then it is already too late.',
  },
  {
    folder: 'tabaxis',
    nameFr: 'Tabaxis',
    nameEn: 'Tabaxi',
    descriptionFr:
      "Griffes, équilibre et curiosité : ils frappent avant qu'on ait fini de les regarder.",
    descriptionEn:
      'Claws, balance and curiosity: they strike before you have finished looking at them.',
  },
  {
    folder: 'fairies',
    nameFr: 'Fées',
    nameEn: 'Fairies',
    descriptionFr:
      'Minuscules et rarement gentilles : de la rosée, des épines et des tours joués aux géants.',
    descriptionEn:
      'Tiny and rarely kind: dew, thorns and tricks played on giants.',
  },
  {
    folder: 'centaurs',
    nameFr: 'Centaures',
    nameEn: 'Centaurs',
    descriptionFr:
      'Sabot, arc et ciel étoilé : la horde galope loin et tire plus loin encore.',
    descriptionEn:
      'Hoof, bow and starry sky: the herd gallops far and shoots farther still.',
  },
  {
    folder: 'dryads',
    nameFr: 'Dryades',
    nameEn: 'Dryads',
    descriptionFr:
      "Nées d'un arbre et mortes avec lui : elles soignent la forêt et étranglent qui l'entame.",
    descriptionEn:
      'Born of a tree and dying with it: they heal the forest and strangle whoever cuts into it.',
  },
  {
    folder: 'kitsunes',
    nameFr: 'Kitsunes',
    nameEn: 'Kitsune',
    descriptionFr:
      "Une queue par siècle de ruse : rien de ce qu'elles montrent n'est tout à fait réel.",
    descriptionEn:
      'One tail per century of cunning: nothing they show you is entirely real.',
  },
  {
    folder: 'draenei',
    nameFr: 'Draenei',
    nameEn: 'Draenei',
    descriptionFr:
      "Exilés d'un monde brisé : la foi leur tient lieu d'armure, et l'armure est épaisse.",
    descriptionEn:
      'Exiles from a shattered world: faith serves as their armor, and the armor is thick.',
  },
  {
    folder: 'lamias',
    nameFr: 'Lamia',
    nameEn: 'Lamia',
    descriptionFr:
      'Anneaux patients et regard fixe : elles enlacent bien avant de mordre.',
    descriptionEn:
      'Patient coils and a fixed gaze: they embrace long before they bite.',
  },
]

/** Clé : le code d'image de la carte (`<code>.png`), comme `CARDS[].id`. */
export const IMPORTED_CARD_NAMES: Readonly<
  Record<string, { nameFr: string; nameEn: string }>
> = {
  'GOB-001': { nameFr: 'Grik le Pillard', nameEn: 'Grik the Raider' },
  'GOB-002': { nameFr: 'Zog Dent-Tordue', nameEn: 'Zog Crooked-Tooth' },
  'GOB-003': { nameFr: 'Snik le Voleur', nameEn: 'Snik the Thief' },
  'GOB-004': { nameFr: 'Gilda la Chasseuse', nameEn: 'Gilda the Huntress' },
  'GOB-005': { nameFr: 'Grik', nameEn: 'Grik' },
  'GOB-006': { nameFr: 'Zog', nameEn: 'Zog' },
  'GOB-007': { nameFr: 'Murg', nameEn: 'Murg' },
  'GOB-008': { nameFr: 'Krix', nameEn: 'Krix' },
  'GOB-009': { nameFr: 'Snik', nameEn: 'Snik' },
  'GOB-010': { nameFr: 'Brak', nameEn: 'Brak' },
  'GOB-011': { nameFr: 'Skar', nameEn: 'Skar' },
  'GOB-012': { nameFr: 'Wort', nameEn: 'Wort' },
  'GOB-013': { nameFr: 'Razz', nameEn: 'Razz' },
  'GOB-014': { nameFr: 'Mog', nameEn: 'Mog' },
  'GOB-015': { nameFr: 'Trog', nameEn: 'Trog' },
  'GOB-016': { nameFr: 'Glob', nameEn: 'Glob' },
  'GOB-017': { nameFr: 'Pob le Cogneur', nameEn: 'Pob the Basher' },
  'GOB-018': { nameFr: 'Nibz', nameEn: 'Nibz' },
  'GOB-019': { nameFr: 'Gritz', nameEn: 'Gritz' },
  'GOB-020': { nameFr: 'Snot', nameEn: 'Snot' },
  'GOB-021': { nameFr: 'Zrik', nameEn: 'Zrik' },
  'GOB-022': { nameFr: 'Nogg', nameEn: 'Nogg' },
  'GOB-023': { nameFr: 'Skab', nameEn: 'Skab' },
  'GOB-024': { nameFr: 'Zik Double-Dague', nameEn: 'Zik Twin-Dagger' },
  'GOB-025': { nameFr: 'Murg le Chaman', nameEn: 'Murg the Shaman' },
  'GOB-026': { nameFr: 'Nix la Sorcière', nameEn: 'Nix the Witch' },
  'GOB-027': { nameFr: 'Brak Casse-Crâne', nameEn: 'Brak Skull-Cracker' },
  'GOB-028': { nameFr: "Mizzra l'Alchimiste", nameEn: 'Mizzra the Alchemist' },
  'GOB-029': { nameFr: 'Grubz', nameEn: 'Grubz' },
  'GOB-030': { nameFr: 'Rizz', nameEn: 'Rizz' },
  'GOB-031': { nameFr: 'Krix Chef-de-Guerre', nameEn: 'Krix Warchief' },
  'GOB-032': { nameFr: 'Yzma la Matriarche', nameEn: 'Yzma the Matriarch' },
  'GOB-033': { nameFr: 'Razka la Cheffe', nameEn: 'Razka the Chieftain' },
  'GOB-034': { nameFr: 'Klob', nameEn: 'Klob' },
  'GOB-035': { nameFr: "Vrax l'Ancien", nameEn: 'Vrax the Elder' },
  'ELF-001': { nameFr: "Lirael l'Archère", nameEn: 'Lirael the Archer' },
  'ELF-002': { nameFr: "Thalion l'Éclaireur", nameEn: 'Thalion the Scout' },
  'ELF-003': {
    nameFr: 'Caladwen la Sentinelle',
    nameEn: 'Caladwen the Sentinel',
  },
  'ELF-004': { nameFr: 'Aelar', nameEn: 'Aelar' },
  'ELF-005': { nameFr: 'Faelar', nameEn: 'Faelar' },
  'ELF-006': { nameFr: 'Thalion', nameEn: 'Thalion' },
  'ELF-007': { nameFr: 'Erevan', nameEn: 'Erevan' },
  'ELF-008': { nameFr: 'Caelum', nameEn: 'Caelum' },
  'ELF-009': { nameFr: 'Luthien', nameEn: 'Luthien' },
  'ELF-010': { nameFr: 'Aerin', nameEn: 'Aerin' },
  'ELF-011': { nameFr: 'Sylvara', nameEn: 'Sylvara' },
  'ELF-012': { nameFr: 'Elwen', nameEn: 'Elwen' },
  'ELF-013': { nameFr: 'Nimwe', nameEn: 'Nimwe' },
  'ELF-014': { nameFr: 'Faenya', nameEn: 'Faenya' },
  'ELF-015': { nameFr: 'Ariel', nameEn: 'Ariel' },
  'ELF-016': { nameFr: 'Thoren aux Couteaux', nameEn: 'Thoren of the Knives' },
  'ELF-017': { nameFr: 'Galad', nameEn: 'Galad' },
  'ELF-018': { nameFr: 'Mirae', nameEn: 'Mirae' },
  'ELF-019': { nameFr: 'Eladrin', nameEn: 'Eladrin' },
  'ELF-020': { nameFr: 'Aelire', nameEn: 'Aelire' },
  'ELF-021': { nameFr: 'Faevyn', nameEn: 'Faevyn' },
  'ELF-022': { nameFr: 'Thandor', nameEn: 'Thandor' },
  'ELF-023': { nameFr: 'Faryn au Naginata', nameEn: 'Faryn of the Naginata' },
  'ELF-024': {
    nameFr: 'Sylvenwen la Prêtresse',
    nameEn: 'Sylvenwen the Priestess',
  },
  'ELF-025': { nameFr: 'Faelar le Mage', nameEn: 'Faelar the Mage' },
  'ELF-026': { nameFr: 'Naïa la Druidesse', nameEn: 'Naïa the Druid' },
  'ELF-027': { nameFr: 'Aerith la Lame', nameEn: 'Aerith the Blade' },
  'ELF-028': { nameFr: 'Erevys', nameEn: 'Erevys' },
  'ELF-029': { nameFr: 'Caelith', nameEn: 'Caelith' },
  'ELF-030': { nameFr: 'Sael Lame-de-Lune', nameEn: 'Sael Moonblade' },
  'ELF-031': { nameFr: "Maelle l'Érudite", nameEn: 'Maelle the Scholar' },
  'ELF-032': { nameFr: 'Erendil Vive-Lame', nameEn: 'Erendil Quickblade' },
  'ELF-033': { nameFr: 'Elowyn', nameEn: 'Elowyn' },
  'ELF-034': { nameFr: 'Reine Aelithia', nameEn: 'Queen Aelithia' },
  'ELF-035': { nameFr: 'Roi Elrandir', nameEn: 'King Elrandir' },
  'ORC-001': { nameFr: 'Grôm la Brute', nameEn: 'Grôm the Brute' },
  'ORC-002': { nameFr: 'Sharga Œil-Borgne', nameEn: 'Sharga One-Eye' },
  'ORC-003': { nameFr: 'Brak le Tambour', nameEn: 'Brak the Drummer' },
  'ORC-004': { nameFr: 'Gor', nameEn: 'Gor' },
  'ORC-005': { nameFr: 'Sharga', nameEn: 'Sharga' },
  'ORC-006': { nameFr: 'Ghaz', nameEn: 'Ghaz' },
  'ORC-007': { nameFr: 'Urza', nameEn: 'Urza' },
  'ORC-008': { nameFr: 'Rok', nameEn: 'Rok' },
  'ORC-009': { nameFr: 'Thok', nameEn: 'Thok' },
  'ORC-010': { nameFr: 'Murz', nameEn: 'Murz' },
  'ORC-011': { nameFr: 'Drak', nameEn: 'Drak' },
  'ORC-012': { nameFr: 'Karg', nameEn: 'Karg' },
  'ORC-013': { nameFr: 'Ushka', nameEn: 'Ushka' },
  'ORC-014': { nameFr: 'Mogra', nameEn: 'Mogra' },
  'ORC-015': { nameFr: 'Brug', nameEn: 'Brug' },
  'ORC-016': { nameFr: 'Snaga', nameEn: 'Snaga' },
  'ORC-017': { nameFr: 'Vrok', nameEn: 'Vrok' },
  'ORC-018': { nameFr: 'Hagga', nameEn: 'Hagga' },
  'ORC-019': { nameFr: 'Gorbag', nameEn: 'Gorbag' },
  'ORC-020': { nameFr: 'Shakka', nameEn: 'Shakka' },
  'ORC-021': { nameFr: 'Ghazruk', nameEn: 'Ghazruk' },
  'ORC-022': { nameFr: 'Grosh Griffes-de-Fer', nameEn: 'Grosh Iron-Claws' },
  'ORC-023': { nameFr: 'Ghazûl le Boucher', nameEn: 'Ghazûl the Butcher' },
  'ORC-024': { nameFr: 'Urza la Guerrière', nameEn: 'Urza the Warrior' },
  'ORC-025': { nameFr: 'Dûrz le Chaman', nameEn: 'Dûrz the Shaman' },
  'ORC-026': { nameFr: 'Urgash', nameEn: 'Urgash' },
  'ORC-027': { nameFr: 'Rokthar', nameEn: 'Rokthar' },
  'ORC-028': { nameFr: 'Maugrim Chef-de-Guerre', nameEn: 'Maugrim Warchief' },
  'ORC-029': { nameFr: "Mok'Tara la Cheffe", nameEn: "Mok'Tara the Chieftain" },
  'ORC-030': { nameFr: "Rok'na la Berserkr", nameEn: "Rok'na the Berserker" },
  'ORC-031': { nameFr: 'Thogg', nameEn: 'Thogg' },
  'ORC-032': {
    nameFr: "Gor'Thak le Dévastateur",
    nameEn: "Gor'Thak the Devastator",
  },
  'DEM-001': { nameFr: 'Démon Soldat', nameEn: 'Demon Soldier' },
  'DEM-002': { nameFr: 'Liraen la Sombre', nameEn: 'Liraen the Dark' },
  'DEM-003': { nameFr: 'Azrael', nameEn: 'Azrael' },
  'DEM-004': { nameFr: 'Lilim', nameEn: 'Lilim' },
  'DEM-005': { nameFr: 'Vorth', nameEn: 'Vorth' },
  'DEM-006': { nameFr: 'Naamah', nameEn: 'Naamah' },
  'DEM-007': { nameFr: 'Belphor', nameEn: 'Belphor' },
  'DEM-008': { nameFr: 'Ronove', nameEn: 'Ronove' },
  'DEM-009': { nameFr: 'Malphas', nameEn: 'Malphas' },
  'DEM-010': { nameFr: 'Verin', nameEn: 'Verin' },
  'DEM-011': { nameFr: 'Astaroth', nameEn: 'Astaroth' },
  'DEM-012': { nameFr: 'Zagan', nameEn: 'Zagan' },
  'DEM-013': { nameFr: 'Eligor', nameEn: 'Eligor' },
  'DEM-014': { nameFr: 'Seere', nameEn: 'Seere' },
  'DEM-015': { nameFr: 'Furcas', nameEn: 'Furcas' },
  'DEM-016': { nameFr: 'Gremory', nameEn: 'Gremory' },
  'DEM-017': { nameFr: 'Vual', nameEn: 'Vual' },
  'DEM-018': { nameFr: 'Azroth', nameEn: 'Azroth' },
  'DEM-019': { nameFr: 'Nyxira', nameEn: 'Nyxira' },
  'DEM-020': { nameFr: 'Vorlok', nameEn: 'Vorlok' },
  'DEM-021': { nameFr: "Belial l'Ailé", nameEn: 'Belial the Winged' },
  'DEM-022': { nameFr: 'Morgath la Sorcière', nameEn: 'Morgath the Witch' },
  'DEM-023': {
    nameFr: 'Naberis la Prêtresse',
    nameEn: 'Naberis the Priestess',
  },
  'DEM-024': { nameFr: 'Naariel', nameEn: 'Naariel' },
  'DEM-025': { nameFr: 'Belzor', nameEn: 'Belzor' },
  'DEM-026': {
    nameFr: 'Azael le Grimorien',
    nameEn: 'Azael the Grimoire-Keeper',
  },
  'DEM-027': { nameFr: 'Chevalier Infernal', nameEn: 'Infernal Knight' },
  'DEM-028': { nameFr: 'Azazel le Warlock', nameEn: 'Azazel the Warlock' },
  'DEM-029': { nameFr: 'Xaphan', nameEn: 'Xaphan' },
  'DEM-030': {
    nameFr: 'Morrigane la Faucheuse',
    nameEn: 'Morrigane the Reaper',
  },
  'DEM-031': { nameFr: 'Baphor, Seigneur Démon', nameEn: 'Baphor, Demon Lord' },
  'DEM-032': {
    nameFr: 'Lilith la Reine Démone',
    nameEn: 'Lilith the Demon Queen',
  },
  'ANG-001': { nameFr: 'Ange Gardien', nameEn: 'Guardian Angel' },
  'ANG-002': { nameFr: 'Gardien Céleste', nameEn: 'Celestial Guardian' },
  'ANG-003': { nameFr: "Lumiel l'Archère", nameEn: 'Lumiel the Archer' },
  'ANG-004': { nameFr: 'Auriel', nameEn: 'Auriel' },
  'ANG-005': { nameFr: 'Cassiel', nameEn: 'Cassiel' },
  'ANG-006': { nameFr: 'Seraphis', nameEn: 'Seraphis' },
  'ANG-007': { nameFr: 'Uriel', nameEn: 'Uriel' },
  'ANG-008': { nameFr: 'Lumiel', nameEn: 'Lumiel' },
  'ANG-009': { nameFr: 'Raziel', nameEn: 'Raziel' },
  'ANG-010': { nameFr: 'Ariel', nameEn: 'Ariel' },
  'ANG-011': { nameFr: 'Nathaniel', nameEn: 'Nathaniel' },
  'ANG-012': { nameFr: 'Zadkiel', nameEn: 'Zadkiel' },
  'ANG-013': { nameFr: 'Camael', nameEn: 'Camael' },
  'ANG-014': { nameFr: 'Selaphiel', nameEn: 'Selaphiel' },
  'ANG-015': { nameFr: 'Jophiel', nameEn: 'Jophiel' },
  'ANG-016': { nameFr: 'Israfel', nameEn: 'Israfel' },
  'ANG-017': { nameFr: 'Gabriel', nameEn: 'Gabriel' },
  'ANG-018': { nameFr: 'Remiel', nameEn: 'Remiel' },
  'ANG-019': { nameFr: 'Auriel', nameEn: 'Auriel' },
  'ANG-020': { nameFr: 'Cassiel', nameEn: 'Cassiel' },
  'ANG-021': { nameFr: 'Seraphis', nameEn: 'Seraphis' },
  'ANG-022': { nameFr: 'Auriel la Guérisseuse', nameEn: 'Auriel the Healer' },
  'ANG-023': { nameFr: 'Sigrun la Valkyrie', nameEn: 'Sigrun the Valkyrie' },
  'ANG-024': { nameFr: 'Uriel', nameEn: 'Uriel' },
  'ANG-025': { nameFr: 'Lumiel', nameEn: 'Lumiel' },
  'ANG-026': {
    nameFr: 'Michael le Protecteur',
    nameEn: 'Michael the Protector',
  },
  'ANG-027': { nameFr: 'Azraël le Déchu', nameEn: 'Azraël the Fallen' },
  'ANG-028': { nameFr: 'Raziel', nameEn: 'Raziel' },
  'ANG-029': { nameFr: 'Séraphin Uriel', nameEn: 'Seraph Uriel' },
  'ANG-030': {
    nameFr: 'Séraphine Reine des Anges',
    nameEn: 'Séraphine, Queen of Angels',
  },
  'DRA-001': { nameFr: 'Vipereau', nameEn: 'Vipereau' },
  'DRA-002': { nameFr: 'Verdoyant', nameEn: 'Verdoyant' },
  'DRA-003': { nameFr: 'Pyrax', nameEn: 'Pyrax' },
  'DRA-004': { nameFr: 'Frosti', nameEn: 'Frosti' },
  'DRA-005': { nameFr: 'Verdax', nameEn: 'Verdax' },
  'DRA-006': { nameFr: 'Skarn', nameEn: 'Skarn' },
  'DRA-007': { nameFr: 'Noxis', nameEn: 'Noxis' },
  'DRA-008': { nameFr: 'Bronz', nameEn: 'Bronz' },
  'DRA-009': { nameFr: 'Glacis', nameEn: 'Glacis' },
  'DRA-010': { nameFr: 'Venn', nameEn: 'Venn' },
  'DRA-011': { nameFr: 'Aurex', nameEn: 'Aurex' },
  'DRA-012': { nameFr: 'Sylvax', nameEn: 'Sylvax' },
  'DRA-013': { nameFr: 'Ignis', nameEn: 'Ignis' },
  'DRA-014': { nameFr: 'Cindra', nameEn: 'Cindra' },
  'DRA-015': { nameFr: 'Vextra', nameEn: 'Vextra' },
  'DRA-016': { nameFr: 'Drakon', nameEn: 'Drakon' },
  'DRA-017': { nameFr: 'Myrr', nameEn: 'Myrr' },
  'DRA-018': { nameFr: 'Pyrax', nameEn: 'Pyrax' },
  'DRA-019': { nameFr: 'Frosti', nameEn: 'Frosti' },
  'DRA-020': { nameFr: 'Verdax', nameEn: 'Verdax' },
  'DRA-021': { nameFr: 'Cendrefeu', nameEn: 'Cendrefeu' },
  'DRA-022': { nameFr: 'Maredrak', nameEn: 'Maredrak' },
  'DRA-023': { nameFr: 'Skarn', nameEn: 'Skarn' },
  'DRA-024': { nameFr: 'Noxis', nameEn: 'Noxis' },
  'DRA-025': { nameFr: 'Givrebise', nameEn: 'Givrebise' },
  'DRA-026': { nameFr: 'Ombrelaile', nameEn: 'Ombrelaile' },
  'DRA-027': { nameFr: 'Foudrelame', nameEn: 'Foudrelame' },
  'DRA-028': { nameFr: 'Bronz', nameEn: 'Bronz' },
  'DRA-029': { nameFr: "Pyraxis l'Ancien", nameEn: 'Pyraxis the Ancient' },
  'DRA-030': { nameFr: "Aurélion l'Astral", nameEn: 'Aurélion the Astral' },
  'NAI-001': { nameFr: 'Borin le Mineur', nameEn: 'Borin the Miner' },
  'NAI-002': { nameFr: 'Durga le Guerrier', nameEn: 'Durga the Warrior' },
  'NAI-003': {
    nameFr: "Torvald l'Arbalétrier",
    nameEn: 'Torvald the Crossbowman',
  },
  'NAI-004': { nameFr: "Astrid l'Exploratrice", nameEn: 'Astrid the Explorer' },
  'NAI-005': { nameFr: 'Borin', nameEn: 'Borin' },
  'NAI-006': { nameFr: 'Durin', nameEn: 'Durin' },
  'NAI-007': { nameFr: 'Thrain', nameEn: 'Thrain' },
  'NAI-008': { nameFr: 'Balin', nameEn: 'Balin' },
  'NAI-009': { nameFr: 'Brokk', nameEn: 'Brokk' },
  'NAI-010': { nameFr: 'Dvalin', nameEn: 'Dvalin' },
  'NAI-011': { nameFr: 'Onar', nameEn: 'Onar' },
  'NAI-012': { nameFr: 'Helga', nameEn: 'Helga' },
  'NAI-013': { nameFr: 'Brunhild', nameEn: 'Brunhild' },
  'NAI-014': { nameFr: 'Sigrun', nameEn: 'Sigrun' },
  'NAI-015': { nameFr: 'Disa', nameEn: 'Disa' },
  'NAI-016': { nameFr: 'Hilda', nameEn: 'Hilda' },
  'NAI-017': { nameFr: 'Greta', nameEn: 'Greta' },
  'NAI-018': { nameFr: 'Torgar', nameEn: 'Torgar' },
  'NAI-019': { nameFr: 'Nain', nameEn: 'Nain' },
  'NAI-020': { nameFr: 'Borin', nameEn: 'Borin' },
  'NAI-021': { nameFr: 'Durin', nameEn: 'Durin' },
  'NAI-022': { nameFr: 'Thrain', nameEn: 'Thrain' },
  'NAI-023': { nameFr: 'Forgemaître Brokk', nameEn: 'Forgemaster Brokk' },
  'NAI-024': { nameFr: 'Helga Marteau-de-Fer', nameEn: 'Helga Iron-Hammer' },
  'NAI-025': { nameFr: 'Dvalin le Runiste', nameEn: 'Dvalin the Runesmith' },
  'NAI-026': { nameFr: 'Sigrid la Prêtresse', nameEn: 'Sigrid the Priestess' },
  'NAI-027': { nameFr: 'Balin', nameEn: 'Balin' },
  'NAI-028': { nameFr: 'Brokk', nameEn: 'Brokk' },
  'NAI-029': { nameFr: 'Thrain Briseroc', nameEn: 'Thrain Rockbreaker' },
  'NAI-030': { nameFr: 'Dvalin', nameEn: 'Dvalin' },
  'NAI-031': { nameFr: 'Roi Khazadûm', nameEn: 'King Khazadûm' },
  'NAI-032': { nameFr: 'Reine Brunhilde', nameEn: 'Queen Brunhilde' },
  'MOR-001': { nameFr: 'Squelette Soldat', nameEn: 'Skeleton Soldier' },
  'MOR-002': { nameFr: 'Goule Affamée', nameEn: 'Starving Ghoul' },
  'MOR-003': { nameFr: 'Spectre Errant', nameEn: 'Wandering Specter' },
  'MOR-004': { nameFr: 'Mordred', nameEn: 'Mordred' },
  'MOR-005': { nameFr: 'Lazarus', nameEn: 'Lazarus' },
  'MOR-006': { nameFr: 'Morwen', nameEn: 'Morwen' },
  'MOR-007': { nameFr: 'Ravenna', nameEn: 'Ravenna' },
  'MOR-008': { nameFr: 'Grimm', nameEn: 'Grimm' },
  'MOR-009': { nameFr: 'Mortis', nameEn: 'Mortis' },
  'MOR-010': { nameFr: 'Korrin', nameEn: 'Korrin' },
  'MOR-011': { nameFr: 'Vael', nameEn: 'Vael' },
  'MOR-012': { nameFr: 'Drusca', nameEn: 'Drusca' },
  'MOR-013': { nameFr: 'Ashen', nameEn: 'Ashen' },
  'MOR-014': { nameFr: 'Sorrow', nameEn: 'Sorrow' },
  'MOR-015': { nameFr: 'Wraithe', nameEn: 'Wraithe' },
  'MOR-016': { nameFr: 'Pale', nameEn: 'Pale' },
  'MOR-017': { nameFr: 'Dreza', nameEn: 'Dreza' },
  'MOR-018': { nameFr: 'Nyx', nameEn: 'Nyx' },
  'MOR-019': { nameFr: 'Mordred', nameEn: 'Mordred' },
  'MOR-020': { nameFr: 'Lazarus', nameEn: 'Lazarus' },
  'MOR-021': { nameFr: 'Morwen', nameEn: 'Morwen' },
  'MOR-022': { nameFr: 'Nécromancien Vael', nameEn: 'Necromancer Vael' },
  'MOR-023': { nameFr: 'Banshee Hurlante', nameEn: 'Howling Banshee' },
  'MOR-024': {
    nameFr: 'Lenore la Nécromancienne',
    nameEn: 'Lenore the Necromancer',
  },
  'MOR-025': { nameFr: 'Ravenna', nameEn: 'Ravenna' },
  'MOR-026': { nameFr: 'Grimm', nameEn: 'Grimm' },
  'MOR-027': { nameFr: 'Néphra la Liseuse', nameEn: 'Néphra the Reader' },
  'MOR-028': { nameFr: 'Chevalier de la Mort', nameEn: 'Death Knight' },
  'MOR-029': { nameFr: 'Carmilla la Vampire', nameEn: 'Carmilla the Vampire' },
  'MOR-030': { nameFr: 'Mortis', nameEn: 'Mortis' },
  'MOR-031': { nameFr: 'Liche Mordrak', nameEn: 'Lich Mordrak' },
  'MOR-032': { nameFr: 'Seigneur-Liche Azrak', nameEn: 'Lich Lord Azrak' },
  'PUA-001': { nameFr: "Zuka l'Éclaireuse", nameEn: 'Zuka the Scout' },
  'PUA-002': { nameFr: 'Tomo le Guetteur', nameEn: 'Tomo the Lookout' },
  'PUA-003': { nameFr: 'Dorn le Chasseur', nameEn: 'Dorn the Hunter' },
  'PUA-004': { nameFr: 'Zuka', nameEn: 'Zuka' },
  'PUA-005': { nameFr: 'Tomo', nameEn: 'Tomo' },
  'PUA-006': { nameFr: 'Nyssi', nameEn: 'Nyssi' },
  'PUA-007': { nameFr: 'Kael', nameEn: 'Kael' },
  'PUA-008': { nameFr: 'Ravi', nameEn: 'Ravi' },
  'PUA-009': { nameFr: 'Dorn', nameEn: 'Dorn' },
  'PUA-010': { nameFr: 'Sylwa', nameEn: 'Sylwa' },
  'PUA-011': { nameFr: 'Iliane', nameEn: 'Iliane' },
  'PUA-012': { nameFr: 'Mira', nameEn: 'Mira' },
  'PUA-013': { nameFr: 'Naxi', nameEn: 'Naxi' },
  'PUA-014': { nameFr: 'Tuli', nameEn: 'Tuli' },
  'PUA-015': { nameFr: 'Oren', nameEn: 'Oren' },
  'PUA-016': { nameFr: 'Ketu au Kunai', nameEn: 'Ketu of the Kunai' },
  'PUA-017': { nameFr: 'Pavi', nameEn: 'Pavi' },
  'PUA-018': { nameFr: 'Suki', nameEn: 'Suki' },
  'PUA-019': { nameFr: 'Lirae', nameEn: 'Lirae' },
  'PUA-020': { nameFr: 'Zuka', nameEn: 'Zuka' },
  'PUA-021': { nameFr: 'Tomo', nameEn: 'Tomo' },
  'PUA-022': { nameFr: 'Nyssi', nameEn: 'Nyssi' },
  'PUA-023': { nameFr: 'Suvi au Chakram', nameEn: 'Suvi of the Chakram' },
  'PUA-024': { nameFr: 'Nyssi la Sorcière', nameEn: 'Nyssi the Witch' },
  'PUA-025': { nameFr: 'Kael la Lame', nameEn: 'Kael the Blade' },
  'PUA-026': { nameFr: 'Sylwa la Chamane', nameEn: 'Sylwa the Shaman' },
  'PUA-027': { nameFr: 'Kael', nameEn: 'Kael' },
  'PUA-028': { nameFr: 'Ravi', nameEn: 'Ravi' },
  'PUA-029': { nameFr: 'Aeshma au Grimoire', nameEn: 'Aeshma of the Grimoire' },
  'PUA-030': { nameFr: 'Ravi la Danseuse', nameEn: 'Ravi the Dancer' },
  'PUA-031': { nameFr: 'Iliane la Prêtresse', nameEn: 'Iliane the Priestess' },
  'PUA-032': { nameFr: 'Dorn', nameEn: 'Dorn' },
  'PUA-033': {
    nameFr: 'Vaeli la Reine Puazi',
    nameEn: 'Vaeli the Puazi Queen',
  },
  'SIR-001': {
    nameFr: 'Nerissa la Gardienne des Récifs',
    nameEn: 'Nerissa the Reef Warden',
  },
  'SIR-002': { nameFr: 'Nérée', nameEn: 'Nérée' },
  'SIR-003': { nameFr: 'Ondaline', nameEn: 'Ondaline' },
  'SIR-004': {
    nameFr: "Thalassa l'Enchanteresse",
    nameEn: 'Thalassa the Enchantress',
  },
  'SIR-005': { nameFr: 'Triton', nameEn: 'Triton' },
  'SIR-006': { nameFr: 'Delphin', nameEn: 'Delphin' },
  'SIR-007': { nameFr: 'Undyne la Prêtresse', nameEn: 'Undyne the Priestess' },
  'SIR-008': { nameFr: 'Sirena', nameEn: 'Sirena' },
  'SIR-009': { nameFr: 'Bathys', nameEn: 'Bathys' },
  'SIR-010': {
    nameFr: 'Perla la Gardienne des Récifs',
    nameEn: 'Perla the Reef Warden',
  },
  'SIR-011': { nameFr: 'Glaucos', nameEn: 'Glaucos' },
  'SIR-012': { nameFr: 'Océane', nameEn: 'Océane' },
  'SIR-013': {
    nameFr: "Calypso l'Enchanteresse",
    nameEn: 'Calypso the Enchantress',
  },
  'SIR-014': { nameFr: 'Palémon', nameEn: 'Palémon' },
  'SIR-015': { nameFr: 'Nérite', nameEn: 'Nérite' },
  'SIR-016': { nameFr: 'Calypsa', nameEn: 'Calypsa' },
  'SIR-017': { nameFr: 'Ondine', nameEn: 'Ondine' },
  'SIR-018': { nameFr: 'Alcyon', nameEn: 'Alcyon' },
  'SIR-019': {
    nameFr: 'Meredith la Prêtresse',
    nameEn: 'Meredith the Priestess',
  },
  'SIR-020': { nameFr: 'Naida', nameEn: 'Naida' },
  'SIR-021': { nameFr: 'Thaumas', nameEn: 'Thaumas' },
  'SIR-022': { nameFr: 'Phorcys', nameEn: 'Phorcys' },
  'SIR-023': { nameFr: 'Pontos', nameEn: 'Pontos' },
  'SIR-024': { nameFr: 'Parthénope', nameEn: 'Parthénope' },
  'SIR-025': { nameFr: 'Abyssa', nameEn: 'Abyssa' },
  'SIR-026': {
    nameFr: "Leucosia l'Enchanteresse",
    nameEn: 'Leucosia the Enchantress',
  },
  'SIR-027': { nameFr: 'Protée le Lancier', nameEn: 'Protée the Lancer' },
  'SIR-028': { nameFr: 'Mélicerte le Rôdeur', nameEn: 'Mélicerte the Ranger' },
  'SIR-029': {
    nameFr: 'Coralind la Prêtresse',
    nameEn: 'Coralind the Priestess',
  },
  'SIR-030': { nameFr: "Maris l'Ondine", nameEn: 'Maris the Undine' },
  'SIR-031': { nameFr: 'Corallia la Chanteuse', nameEn: 'Corallia the Singer' },
  'SIR-032': {
    nameFr: 'Thétys la Sorcière des Abysses',
    nameEn: 'Thétys the Abyssal Witch',
  },
  'SIR-033': {
    nameFr: 'Océanos le Rempart des Récifs',
    nameEn: 'Océanos, Bulwark of the Reefs',
  },
  'SIR-034': {
    nameFr: 'Galatée la Chasseresse',
    nameEn: 'Galatée the Huntress',
  },
  'SIR-035': { nameFr: 'Doris la Chanteuse', nameEn: 'Doris the Singer' },
  'TAB-001': { nameFr: 'Raksha la Rôdeuse', nameEn: 'Raksha the Ranger' },
  'TAB-002': { nameFr: 'Kiro', nameEn: 'Kiro' },
  'TAB-003': { nameFr: 'Mirri', nameEn: 'Mirri' },
  'TAB-004': { nameFr: 'Rael le Duelliste', nameEn: 'Rael the Duelist' },
  'TAB-005': { nameFr: 'Tavi', nameEn: 'Tavi' },
  'TAB-006': { nameFr: 'Sylas', nameEn: 'Sylas' },
  'TAB-007': { nameFr: 'Nala la Nomade', nameEn: 'Nala the Nomad' },
  'TAB-008': { nameFr: 'Leontis', nameEn: 'Leontis' },
  'TAB-009': { nameFr: 'Sabra', nameEn: 'Sabra' },
  'TAB-010': { nameFr: 'Pardus le Rôdeur', nameEn: 'Pardus the Ranger' },
  'TAB-011': { nameFr: 'Nima', nameEn: 'Nima' },
  'TAB-012': { nameFr: 'Kaelen', nameEn: 'Kaelen' },
  'TAB-013': { nameFr: 'Tamsin la Duelliste', nameEn: 'Tamsin the Duelist' },
  'TAB-014': { nameFr: 'Sabal', nameEn: 'Sabal' },
  'TAB-015': { nameFr: 'Sekha', nameEn: 'Sekha' },
  'TAB-016': { nameFr: 'Ashira', nameEn: 'Ashira' },
  'TAB-017': { nameFr: 'Ravan le Nomade', nameEn: 'Ravan the Nomad' },
  'TAB-018': { nameFr: 'Bastet', nameEn: 'Bastet' },
  'TAB-019': { nameFr: 'Mizu', nameEn: 'Mizu' },
  'TAB-020': { nameFr: 'Nefer la Rôdeuse', nameEn: 'Nefer the Ranger' },
  'TAB-021': { nameFr: 'Tigris', nameEn: 'Tigris' },
  'TAB-022': { nameFr: 'Korat', nameEn: 'Korat' },
  'TAB-023': { nameFr: 'Karrol', nameEn: 'Karrol' },
  'TAB-024': { nameFr: 'Zephyr le Duelliste', nameEn: 'Zephyr the Duelist' },
  'TAB-025': { nameFr: 'Suri la Gardienne', nameEn: 'Suri the Guardian' },
  'TAB-026': { nameFr: 'Rhazan le Chaman', nameEn: 'Rhazan the Shaman' },
  'TAB-027': { nameFr: 'Ocelia la Nomade', nameEn: 'Ocelia the Nomad' },
  'TAB-028': { nameFr: 'Tibbar le Voleur', nameEn: 'Tibbar the Thief' },
  'TAB-029': { nameFr: 'Suria la Chasseresse', nameEn: 'Suria the Huntress' },
  'TAB-030': { nameFr: 'Keshin le Rôdeur', nameEn: 'Keshin the Ranger' },
  'TAB-031': { nameFr: 'Keshari la Bondissante', nameEn: 'Keshari the Leaper' },
  'TAB-032': { nameFr: "Mauro l'Archer", nameEn: 'Mauro the Archer' },
  'FEE-001': { nameFr: 'Sylvain', nameEn: 'Sylvain' },
  'FEE-002': { nameFr: 'Lys', nameEn: 'Lys' },
  'FEE-003': { nameFr: 'Aubépin', nameEn: 'Aubépin' },
  'FEE-004': { nameFr: 'Rosée la Bretteuse', nameEn: 'Rosée the Swordswoman' },
  'FEE-005': { nameFr: 'Genêt', nameEn: 'Genêt' },
  'FEE-006': { nameFr: 'Fougère', nameEn: 'Fougère' },
  'FEE-007': { nameFr: 'Houx', nameEn: 'Houx' },
  'FEE-008': { nameFr: 'Iris', nameEn: 'Iris' },
  'FEE-009': { nameFr: 'Cyprès', nameEn: 'Cyprès' },
  'FEE-010': {
    nameFr: 'Chardon la Tisseuse de Sorts',
    nameEn: 'Chardon the Spellweaver',
  },
  'FEE-011': { nameFr: 'Osmond', nameEn: 'Osmond' },
  'FEE-012': { nameFr: 'Astérie', nameEn: 'Astérie' },
  'FEE-013': { nameFr: 'Mélilot', nameEn: 'Mélilot' },
  'FEE-014': { nameFr: 'Flora', nameEn: 'Flora' },
  'FEE-015': { nameFr: 'Lilas', nameEn: 'Lilas' },
  'FEE-016': { nameFr: 'Aubépine', nameEn: 'Aubépine' },
  'FEE-017': { nameFr: 'Nébule', nameEn: 'Nébule' },
  'FEE-018': { nameFr: 'Sorbe', nameEn: 'Sorbe' },
  'FEE-019': { nameFr: 'Nard', nameEn: 'Nard' },
  'FEE-020': { nameFr: 'Sylphine', nameEn: 'Sylphine' },
  'FEE-021': { nameFr: 'Nyssa', nameEn: 'Nyssa' },
  'FEE-022': { nameFr: 'Thymel', nameEn: 'Thymel' },
  'FEE-023': { nameFr: 'Amaryllis', nameEn: 'Amaryllis' },
  'FEE-024': { nameFr: 'Trèfle', nameEn: 'Trèfle' },
  'FEE-025': { nameFr: 'Gwenn', nameEn: 'Gwenn' },
  'FEE-026': { nameFr: 'Sorbin', nameEn: 'Sorbin' },
  'FEE-027': { nameFr: 'Glycine la Gardienne', nameEn: 'Glycine the Guardian' },
  'FEE-028': { nameFr: 'Primevère la Fée', nameEn: 'Primevère the Fairy' },
  'FEE-029': { nameFr: 'Vernal', nameEn: 'Vernal' },
  'FEE-030': { nameFr: 'Genièvre la Ronce', nameEn: 'Genièvre the Bramble' },
  'FEE-031': { nameFr: 'Ombrelle', nameEn: 'Ombrelle' },
  'FEE-032': { nameFr: 'Aubran', nameEn: 'Aubran' },
  'FEE-033': {
    nameFr: 'Muguet la Tisseuse de Sorts',
    nameEn: 'Muguet the Spellweaver',
  },
  'FEE-034': { nameFr: 'Estrel', nameEn: 'Estrel' },
  'FEE-035': { nameFr: "Solène l'Aube", nameEn: 'Solène the Dawn' },
  'FEE-036': { nameFr: "Bruyère l'Archère", nameEn: 'Bruyère the Archer' },
  'CEN-001': { nameFr: 'Pholos', nameEn: 'Pholos' },
  'CEN-002': { nameFr: 'Nessa', nameEn: 'Nessa' },
  'CEN-003': { nameFr: 'Kyrian', nameEn: 'Kyrian' },
  'CEN-004': { nameFr: 'Astera', nameEn: 'Astera' },
  'CEN-005': { nameFr: 'Doron', nameEn: 'Doron' },
  'CEN-006': { nameFr: 'Thalia', nameEn: 'Thalia' },
  'CEN-007': { nameFr: 'Menal', nameEn: 'Menal' },
  'CEN-008': { nameFr: 'Iphis', nameEn: 'Iphis' },
  'CEN-009': { nameFr: 'Korax', nameEn: 'Korax' },
  'CEN-010': { nameFr: 'Elara', nameEn: 'Elara' },
  'CEN-011': { nameFr: 'Bryson', nameEn: 'Bryson' },
  'CEN-012': { nameFr: 'Cyrane', nameEn: 'Cyrane' },
  'CEN-013': { nameFr: 'Damon', nameEn: 'Damon' },
  'CEN-014': { nameFr: 'Orithe', nameEn: 'Orithe' },
  'CEN-015': { nameFr: 'Lykos', nameEn: 'Lykos' },
  'CEN-016': { nameFr: 'Kerion', nameEn: 'Kerion' },
  'CEN-017': { nameFr: 'Aithra', nameEn: 'Aithra' },
  'CEN-018': { nameFr: 'Bremos', nameEn: 'Bremos' },
  'CEN-019': { nameFr: 'Eurytos', nameEn: 'Eurytos' },
  'CEN-020': { nameFr: 'Hylea', nameEn: 'Hylea' },
  'CEN-021': { nameFr: 'Antheus', nameEn: 'Antheus' },
  'CEN-022': { nameFr: 'Kalliste', nameEn: 'Kalliste' },
  'CEN-023': { nameFr: 'Peirion', nameEn: 'Peirion' },
  'CEN-024': { nameFr: 'Melanth', nameEn: 'Melanth' },
  'CEN-025': { nameFr: 'Thessala', nameEn: 'Thessala' },
  'CEN-026': { nameFr: 'Asbolos le Devin', nameEn: 'Asbolos the Seer' },
  'CEN-027': { nameFr: 'Nessos', nameEn: 'Nessos' },
  'CEN-028': { nameFr: 'Hylonome', nameEn: 'Hylonome' },
  'CEN-029': { nameFr: 'Pholoé la Traqueuse', nameEn: 'Pholoé the Tracker' },
  'CEN-030': { nameFr: 'Agrios', nameEn: 'Agrios' },
  'CEN-031': {
    nameFr: 'Ourea la Montagnarde',
    nameEn: 'Ourea the Mountaineer',
  },
  'CEN-032': {
    nameFr: 'Nephélé la Fille-des-Nuées',
    nameEn: 'Nephélé, Daughter of the Clouds',
  },
  'CEN-033': {
    nameFr: 'Eurytion le Brise-Lance',
    nameEn: 'Eurytion the Lance-Breaker',
  },
  'CEN-034': { nameFr: "Hippé l'Astronome", nameEn: 'Hippé the Astronomer' },
  'CEN-035': { nameFr: 'Chiron le Sage', nameEn: 'Chiron the Sage' },
  'DRY-001': { nameFr: 'Sylvane', nameEn: 'Sylvane' },
  'DRY-002': { nameFr: 'Bruyère', nameEn: 'Bruyère' },
  'DRY-003': { nameFr: 'Aubépine', nameEn: 'Aubépine' },
  'DRY-004': { nameFr: 'Fougère', nameEn: 'Fougère' },
  'DRY-005': { nameFr: 'Noisette', nameEn: 'Noisette' },
  'DRY-006': { nameFr: 'Ronce', nameEn: 'Ronce' },
  'DRY-007': { nameFr: 'Mélisse', nameEn: 'Mélisse' },
  'DRY-008': { nameFr: 'Aulne', nameEn: 'Aulne' },
  'DRY-009': { nameFr: 'Garance', nameEn: 'Garance' },
  'DRY-010': { nameFr: 'Prunelle', nameEn: 'Prunelle' },
  'DRY-011': { nameFr: 'Verveine', nameEn: 'Verveine' },
  'DRY-012': { nameFr: 'Églantine', nameEn: 'Églantine' },
  'DRY-013': { nameFr: 'Myrte', nameEn: 'Myrte' },
  'DRY-014': { nameFr: 'Sorbier', nameEn: 'Sorbier' },
  'DRY-015': { nameFr: 'Osier', nameEn: 'Osier' },
  'DRY-016': { nameFr: 'Camélia', nameEn: 'Camélia' },
  'DRY-017': { nameFr: 'Chardon', nameEn: 'Chardon' },
  'DRY-018': { nameFr: 'Belladone', nameEn: 'Belladone' },
  'DRY-019': { nameFr: 'Digitale', nameEn: 'Digitale' },
  'DRY-020': { nameFr: 'Angélique', nameEn: 'Angélique' },
  'DRY-021': { nameFr: 'Cormier', nameEn: 'Cormier' },
  'DRY-022': { nameFr: 'Viorne', nameEn: 'Viorne' },
  'DRY-023': { nameFr: 'Sureau', nameEn: 'Sureau' },
  'DRY-024': { nameFr: 'Amarante la Tisseuse', nameEn: 'Amarante the Weaver' },
  'DRY-025': { nameFr: 'Hellébore', nameEn: 'Hellébore' },
  'DRY-026': { nameFr: 'Chênaie la Gardienne', nameEn: 'Chênaie the Guardian' },
  'DRY-027': { nameFr: 'Absinthe', nameEn: 'Absinthe' },
  'DRY-028': { nameFr: 'Glycine', nameEn: 'Glycine' },
  'DRY-029': { nameFr: 'Lierre la Rampante', nameEn: 'Lierre the Creeper' },
  'DRY-030': { nameFr: 'Dryas la Sève-Ancienne', nameEn: 'Dryas Elder-Sap' },
  'DRY-031': { nameFr: 'Ormeval le Cœur-de-Bois', nameEn: 'Ormeval Heartwood' },
  'DRY-032': {
    nameFr: 'Térébinthe la Floraison',
    nameEn: 'Térébinthe the Blossoming',
  },
  'DRY-033': {
    nameFr: "Ygdrane l'Arbre-Mère",
    nameEn: 'Ygdrane the Mother-Tree',
  },
  'DRY-034': { nameFr: 'Amalia', nameEn: 'Amalia' },
  'KIT-001': { nameFr: 'Akane', nameEn: 'Akane' },
  'KIT-002': { nameFr: 'Kohaku', nameEn: 'Kohaku' },
  'KIT-003': { nameFr: 'Suzume', nameEn: 'Suzume' },
  'KIT-004': { nameFr: 'Ren', nameEn: 'Ren' },
  'KIT-005': { nameFr: 'Yuki', nameEn: 'Yuki' },
  'KIT-006': { nameFr: 'Haruki', nameEn: 'Haruki' },
  'KIT-007': { nameFr: 'Mei', nameEn: 'Mei' },
  'KIT-008': { nameFr: 'Sora', nameEn: 'Sora' },
  'KIT-009': { nameFr: 'Tsubaki', nameEn: 'Tsubaki' },
  'KIT-010': { nameFr: 'Kaede', nameEn: 'Kaede' },
  'KIT-011': { nameFr: 'Riku', nameEn: 'Riku' },
  'KIT-012': { nameFr: 'Nozomi', nameEn: 'Nozomi' },
  'KIT-013': { nameFr: 'Shino', nameEn: 'Shino' },
  'KIT-014': { nameFr: 'Takumi', nameEn: 'Takumi' },
  'KIT-015': { nameFr: 'Ayame', nameEn: 'Ayame' },
  'KIT-016': { nameFr: 'Yumiko', nameEn: 'Yumiko' },
  'KIT-017': { nameFr: 'Daichi', nameEn: 'Daichi' },
  'KIT-018': { nameFr: 'Kagura', nameEn: 'Kagura' },
  'KIT-019': { nameFr: 'Hoshimi', nameEn: 'Hoshimi' },
  'KIT-020': { nameFr: 'Sen', nameEn: 'Sen' },
  'KIT-021': { nameFr: 'Yorishiro', nameEn: 'Yorishiro' },
  'KIT-022': { nameFr: 'Fumika', nameEn: 'Fumika' },
  'KIT-023': { nameFr: 'Rensuke', nameEn: 'Rensuke' },
  'KIT-024': { nameFr: 'Reika', nameEn: 'Reika' },
  'KIT-025': { nameFr: 'Inari la Gardienne', nameEn: 'Inari the Guardian' },
  'KIT-026': { nameFr: 'Byakko', nameEn: 'Byakko' },
  'KIT-027': { nameFr: 'Shirayuki', nameEn: 'Shirayuki' },
  'KIT-028': { nameFr: 'Genshin le Rusé', nameEn: 'Genshin the Cunning' },
  'KIT-029': { nameFr: 'Amaterine', nameEn: 'Amaterine' },
  'KIT-030': { nameFr: 'Hiroto', nameEn: 'Hiroto' },
  'KIT-031': {
    nameFr: 'Kuzunoha la Mère des Brumes',
    nameEn: 'Kuzunoha, Mother of Mists',
  },
  'KIT-032': {
    nameFr: 'Ryōen le Porte-Braise',
    nameEn: 'Ryōen the Ember-Bearer',
  },
  'KIT-033': {
    nameFr: 'Tamaki la Diseuse',
    nameEn: 'Tamaki the Fortune-Teller',
  },
  'KIT-034': { nameFr: 'Tamamo-no-Mae', nameEn: 'Tamamo-no-Mae' },
  'DRE-001': {
    nameFr: 'Karaan le Vindicateur',
    nameEn: 'Karaan the Vindicator',
  },
  'DRE-002': { nameFr: 'Iridi la Chasseresse', nameEn: 'Iridi the Huntress' },
  'DRE-003': {
    nameFr: 'Dorelei la Prêtresse',
    nameEn: 'Dorelei the Priestess',
  },
  'DRE-004': { nameFr: 'Auchindra', nameEn: 'Auchindra' },
  'DRE-005': { nameFr: 'Nelth', nameEn: 'Nelth' },
  'DRE-006': { nameFr: 'Vorel', nameEn: 'Vorel' },
  'DRE-007': { nameFr: 'Talgath', nameEn: 'Talgath' },
  'DRE-008': { nameFr: 'Yrel', nameEn: 'Yrel' },
  'DRE-009': { nameFr: 'Iridi', nameEn: 'Iridi' },
  'DRE-010': { nameFr: 'Suraia', nameEn: 'Suraia' },
  'DRE-011': { nameFr: 'Dorelei', nameEn: 'Dorelei' },
  'DRE-012': { nameFr: 'Karaan', nameEn: 'Karaan' },
  'DRE-013': { nameFr: 'Nobundo', nameEn: 'Nobundo' },
  'DRE-014': { nameFr: 'Maraad', nameEn: 'Maraad' },
  'DRE-015': { nameFr: 'Veras', nameEn: 'Veras' },
  'DRE-016': { nameFr: 'Naeloni', nameEn: 'Naeloni' },
  'DRE-017': { nameFr: 'Torvash', nameEn: 'Torvash' },
  'DRE-018': { nameFr: 'Khadar', nameEn: 'Khadar' },
  'DRE-019': { nameFr: 'Akama', nameEn: 'Akama' },
  'DRE-020': { nameFr: 'Velara', nameEn: 'Velara' },
  'DRE-021': { nameFr: 'Auchindra', nameEn: 'Auchindra' },
  'DRE-022': { nameFr: 'Nelth', nameEn: 'Nelth' },
  'DRE-023': { nameFr: 'Vorel', nameEn: 'Vorel' },
  'DRE-024': { nameFr: 'Yrelis', nameEn: 'Yrelis' },
  'DRE-025': { nameFr: 'Yrel la Paladin', nameEn: 'Yrel the Paladin' },
  'DRE-026': { nameFr: 'Nobundo le Chaman', nameEn: 'Nobundo the Shaman' },
  'DRE-027': { nameFr: 'Talgath', nameEn: 'Talgath' },
  'DRE-028': { nameFr: 'Yrel', nameEn: 'Yrel' },
  'DRE-029': { nameFr: 'Maraash le Gardien', nameEn: 'Maraash the Guardian' },
  'DRE-030': { nameFr: 'Suraia la Mage', nameEn: 'Suraia the Mage' },
  'DRE-031': { nameFr: 'Maraad le Champion', nameEn: 'Maraad the Champion' },
  'DRE-032': { nameFr: 'Iridi', nameEn: 'Iridi' },
  'DRE-033': { nameFr: 'Velen le Prophète', nameEn: 'Velen the Prophet' },
  'LAM-001': { nameFr: 'Sssira la Chasseresse', nameEn: 'Sssira the Huntress' },
  'LAM-002': { nameFr: 'Naja la Guerrière', nameEn: 'Naja the Warrior' },
  'LAM-003': { nameFr: 'Sssira', nameEn: 'Sssira' },
  'LAM-004': { nameFr: 'Naja', nameEn: 'Naja' },
  'LAM-005': { nameFr: 'Velith', nameEn: 'Velith' },
  'LAM-006': { nameFr: 'Echidna', nameEn: 'Echidna' },
  'LAM-007': { nameFr: 'Sythara', nameEn: 'Sythara' },
  'LAM-008': { nameFr: 'Lamis', nameEn: 'Lamis' },
  'LAM-009': { nameFr: 'Nessaia', nameEn: 'Nessaia' },
  'LAM-010': { nameFr: 'Ophira', nameEn: 'Ophira' },
  'LAM-011': { nameFr: 'Vesna', nameEn: 'Vesna' },
  'LAM-012': { nameFr: 'Saluna', nameEn: 'Saluna' },
  'LAM-013': { nameFr: 'Thessa', nameEn: 'Thessa' },
  'LAM-014': { nameFr: 'Ekiss', nameEn: 'Ekiss' },
  'LAM-015': { nameFr: 'Ophira', nameEn: 'Ophira' },
  'LAM-016': { nameFr: 'Zaleth', nameEn: 'Zaleth' },
  'LAM-017': { nameFr: 'Meressa', nameEn: 'Meressa' },
  'LAM-018': { nameFr: 'Naia', nameEn: 'Naia' },
  'LAM-019': { nameFr: 'Vipra', nameEn: 'Vipra' },
  'LAM-020': { nameFr: 'Morgath', nameEn: 'Morgath' },
  'LAM-021': { nameFr: 'Sssira', nameEn: 'Sssira' },
  'LAM-022': { nameFr: 'Naja', nameEn: 'Naja' },
  'LAM-023': { nameFr: 'Velith', nameEn: 'Velith' },
  'LAM-024': { nameFr: 'Sythra', nameEn: 'Sythra' },
  'LAM-025': { nameFr: 'Velith la Prêtresse', nameEn: 'Velith the Priestess' },
  'LAM-026': { nameFr: "Sythara l'Assassine", nameEn: 'Sythara the Assassin' },
  'LAM-027': { nameFr: 'Nessaia la Mystique', nameEn: 'Nessaia the Mystic' },
  'LAM-028': { nameFr: 'Echidna', nameEn: 'Echidna' },
  'LAM-029': { nameFr: 'Sythara', nameEn: 'Sythara' },
  'LAM-030': { nameFr: 'Nyxara la Vénéneuse', nameEn: 'Nyxara the Venomous' },
  'LAM-031': { nameFr: 'Ophira la Charmeuse', nameEn: 'Ophira the Charmer' },
  'LAM-032': { nameFr: 'Vipra la Gardienne', nameEn: 'Vipra the Guardian' },
  'LAM-033': { nameFr: 'Lamis', nameEn: 'Lamis' },
  'LAM-034': { nameFr: 'Reine Echidna', nameEn: 'Queen Echidna' },
}
