/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedCollectionRouteImport } from './routes/_authenticated/collection'
import { Route as AuthenticatedProfileUsernameRouteImport } from './routes/_authenticated/profile.$username'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionRoute = AuthenticatedCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileUsernameRoute =
  AuthenticatedProfileUsernameRouteImport.update({
    id: '/profile/$username',
    path: '/profile/$username',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/play': typeof AuthenticatedPlayRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/': typeof AuthIndexRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/play': typeof AuthenticatedPlayRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth': typeof AuthIndexRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/_authenticated/collection': typeof AuthenticatedCollectionRoute
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/profile/$username': typeof AuthenticatedProfileUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending'
    | '/register'
    | '/collection'
    | '/play'
    | '/settings'
    | '/auth/'
    | '/profile/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending'
    | '/register'
    | '/collection'
    | '/play'
    | '/settings'
    | '/auth'
    | '/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pending'
    | '/register'
    | '/_authenticated/collection'
    | '/_authenticated/play'
    | '/_authenticated/settings'
    | '/auth/'
    | '/_authenticated/profile/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  RegisterRoute: typeof RegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection': {
      id: '/_authenticated/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof AuthenticatedCollectionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/$username': {
      id: '/_authenticated/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthenticatedProfileUsernameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCollectionRoute: typeof AuthenticatedCollectionRoute
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProfileUsernameRoute: typeof AuthenticatedProfileUsernameRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCollectionRoute: AuthenticatedCollectionRoute,
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProfileUsernameRoute: AuthenticatedProfileUsernameRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  RegisterRoute: RegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
